from app.questions.types import QuestionDefinition, QuestionType, SectionDefinition, SubsectionDefinition

DATA_INSIGHTS_SECTION = SectionDefinition(
    key="data_insights",
    title="Data & Insights",
    description="Configure ASN data feeds, reporting packages, and sustainability dashboards.",
    order=6,
    subsections=[
        # ── ASN (Advance Shipping Notice) ──────────────────────────────
        SubsectionDefinition(
            key="asn",
            title="Advance Shipping Notice (ASN)",
            order=1,
            questions=[
                QuestionDefinition(
                    key="di_asn_realtime_method",
                    section="data_insights",
                    subsection="asn",
                    question_text="Real-time ASN delivery method",
                    question_type=QuestionType.SELECT,
                    options=["API (webhook)", "SFTP", "Not required"],
                    required=True,
                    order=1,
                    target_service="unicorn",
                    config_description="Configure real-time ASN output channel in Unicorn",
                ),
                QuestionDefinition(
                    key="di_asn_realtime_api_url",
                    section="data_insights",
                    subsection="asn",
                    question_text="Real-time ASN API endpoint URL",
                    question_type=QuestionType.TEXT,
                    depends_on={"di_asn_realtime_method": "API (webhook)"},
                    placeholder="https://api.client.com/asn-webhook",
                    order=2,
                    target_service="unicorn",
                    config_description="Set real-time ASN webhook URL in Unicorn",
                ),
                QuestionDefinition(
                    key="di_asn_realtime_auth",
                    section="data_insights",
                    subsection="asn",
                    question_text="Real-time ASN API authentication type",
                    question_type=QuestionType.SELECT,
                    options=["Bearer token", "Basic auth", "API key header", "No auth"],
                    depends_on={"di_asn_realtime_method": "API (webhook)"},
                    order=3,
                    target_service="unicorn",
                    config_description="Set auth method for real-time ASN webhook in Unicorn",
                ),
                QuestionDefinition(
                    key="di_asn_realtime_headers",
                    section="data_insights",
                    subsection="asn",
                    question_text="Real-time ASN API headers",
                    question_type=QuestionType.KEY_VALUE,
                    depends_on={"di_asn_realtime_method": "API (webhook)"},
                    help_text="Add custom headers for the ASN webhook.",
                    order=4,
                    target_service="unicorn",
                    config_description="Set API headers for real-time ASN webhook in Unicorn",
                    field_config={
                        "key_label": "Header Name",
                        "value_label": "Header Value",
                        "key_placeholder": "e.g. Authorization",
                        "value_placeholder": "e.g. Bearer token123",
                        "max_rows": 10,
                    },
                ),
                QuestionDefinition(
                    key="di_asn_realtime_sftp",
                    section="data_insights",
                    subsection="asn",
                    question_text="Real-time ASN SFTP connection details",
                    question_type=QuestionType.OBJECT,
                    depends_on={"di_asn_realtime_method": "SFTP"},
                    order=5,
                    target_service="unicorn",
                    config_description="Set SFTP connection for real-time ASN in Unicorn",
                    field_config={
                        "fields": [
                            {"key": "host", "label": "SFTP Host", "type": "text", "placeholder": "sftp.client.com", "required": True},
                            {"key": "port", "label": "Port", "type": "number", "placeholder": "22", "required": True},
                            {"key": "username", "label": "Username", "type": "text", "placeholder": "sftp_user", "required": True},
                            {"key": "password", "label": "Password", "type": "text", "placeholder": "••••••••", "required": True},
                            {"key": "path", "label": "Remote Path", "type": "text", "placeholder": "/uploads/asn/", "required": False},
                        ]
                    },
                ),
                QuestionDefinition(
                    key="di_asn_datafeed_method",
                    section="data_insights",
                    subsection="asn",
                    question_text="ASN data feed delivery method (batch)",
                    question_type=QuestionType.SELECT,
                    options=["Email", "SFTP", "Not required"],
                    required=True,
                    order=6,
                    target_service="unicorn",
                    config_description="Configure ASN batch feed output channel in Unicorn",
                ),
                QuestionDefinition(
                    key="di_asn_datafeed_emails",
                    section="data_insights",
                    subsection="asn",
                    question_text="ASN data feed email recipients",
                    question_type=QuestionType.EMAIL_LIST,
                    depends_on={"di_asn_datafeed_method": "Email"},
                    help_text="Email addresses that will receive the ASN data feed.",
                    order=7,
                    target_service="unicorn",
                    config_description="Set email recipients for ASN data feed in Unicorn",
                ),
                QuestionDefinition(
                    key="di_asn_datafeed_sftp",
                    section="data_insights",
                    subsection="asn",
                    question_text="ASN data feed SFTP connection details",
                    question_type=QuestionType.OBJECT,
                    depends_on={"di_asn_datafeed_method": "SFTP"},
                    order=8,
                    target_service="unicorn",
                    config_description="Set SFTP connection for ASN data feed in Unicorn",
                    field_config={
                        "fields": [
                            {"key": "host", "label": "SFTP Host", "type": "text", "placeholder": "sftp.client.com", "required": True},
                            {"key": "port", "label": "Port", "type": "number", "placeholder": "22", "required": True},
                            {"key": "username", "label": "Username", "type": "text", "placeholder": "sftp_user", "required": True},
                            {"key": "password", "label": "Password", "type": "text", "placeholder": "••••••••", "required": True},
                            {"key": "path", "label": "Remote Path", "type": "text", "placeholder": "/uploads/asn-feed/", "required": False},
                        ]
                    },
                ),
            ],
        ),
        # ── Reporting ──────────────────────────────────────────────────
        SubsectionDefinition(
            key="reporting",
            title="Reporting",
            order=2,
            questions=[
                QuestionDefinition(
                    key="di_reporting_package",
                    section="data_insights",
                    subsection="reporting",
                    question_text="Which reporting package is required?",
                    question_type=QuestionType.SELECT,
                    options=["Standard", "Premium", "Custom"],
                    required=True,
                    order=1,
                    target_service="unicorn",
                    config_description="Configure reporting tier in Unicorn",
                ),
                QuestionDefinition(
                    key="di_sustainability_dashboard",
                    section="data_insights",
                    subsection="reporting",
                    question_text="Is a sustainability dashboard required?",
                    question_type=QuestionType.BOOLEAN,
                    required=True,
                    help_text="Provides carbon footprint and circular economy metrics.",
                    order=2,
                    target_service="unicorn",
                    config_description="Enable sustainability module in Unicorn reporting",
                ),
                QuestionDefinition(
                    key="di_account_email",
                    section="data_insights",
                    subsection="reporting",
                    question_text="Primary account email for reporting access",
                    question_type=QuestionType.EMAIL,
                    required=True,
                    placeholder="account-manager@client.com",
                    order=3,
                    target_service="unicorn",
                    config_description="Set primary reporting contact in Unicorn",
                ),
                QuestionDefinition(
                    key="di_report_delivery_method",
                    section="data_insights",
                    subsection="reporting",
                    question_text="Report delivery method",
                    question_type=QuestionType.SELECT,
                    options=["Email", "SFTP", "Dashboard only"],
                    required=True,
                    order=4,
                    target_service="unicorn",
                    config_description="Configure report distribution channel in Unicorn",
                ),
                QuestionDefinition(
                    key="di_report_email_recipients",
                    section="data_insights",
                    subsection="reporting",
                    question_text="Report email recipients",
                    question_type=QuestionType.EMAIL_LIST,
                    depends_on={"di_report_delivery_method": "Email"},
                    help_text="Email addresses that will receive scheduled reports.",
                    order=5,
                    target_service="unicorn",
                    config_description="Set email recipients for reports in Unicorn",
                ),
                QuestionDefinition(
                    key="di_report_sftp_ownership",
                    section="data_insights",
                    subsection="reporting",
                    question_text="Who owns the SFTP server for report delivery?",
                    question_type=QuestionType.SELECT,
                    options=["Client-owned", "ReBound-managed"],
                    depends_on={"di_report_delivery_method": "SFTP"},
                    order=6,
                    target_service="unicorn",
                    config_description="Determine SFTP server responsibility for report delivery",
                ),
            ],
        ),
    ],
)
