from app.questions.types import QuestionDefinition, QuestionType, SectionDefinition, SubsectionDefinition

DATA_INSIGHTS_SECTION = SectionDefinition(
    key="data_insights",
    title="Data & Insights",
    description="Configure reporting, data feeds, dashboards, and integration points.",
    order=6,
    subsections=[
        SubsectionDefinition(
            key="reporting",
            title="Reporting",
            order=1,
            questions=[
                QuestionDefinition(
                    key="di_reporting_frequency",
                    section="data_insights",
                    subsection="reporting",
                    question_text="How frequently should reports be generated?",
                    question_type=QuestionType.SELECT,
                    options=["Daily", "Weekly", "Monthly", "On demand"],
                    required=True,
                    help_text="Standard operational reports on return volumes, processing times, and outcomes.",
                    order=1,
                    config_description="Configures reporting schedule in analytics-service",
                ),
                QuestionDefinition(
                    key="di_report_recipients",
                    section="data_insights",
                    subsection="reporting",
                    question_text="Who should receive reports? (email addresses)",
                    question_type=QuestionType.TEXTAREA,
                    required=True,
                    placeholder="one email per line",
                    order=2,
                ),
                QuestionDefinition(
                    key="di_report_types",
                    section="data_insights",
                    subsection="reporting",
                    question_text="Which report types are needed?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=["Volume summary", "Processing SLA", "Grading breakdown", "Return reasons analysis", "Financial reconciliation", "Carrier performance"],
                    required=True,
                    order=3,
                ),
                QuestionDefinition(
                    key="di_custom_reports",
                    section="data_insights",
                    subsection="reporting",
                    question_text="Do you need custom reports beyond the standard set?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No"],
                    required=True,
                    order=4,
                ),
                QuestionDefinition(
                    key="di_custom_report_details",
                    section="data_insights",
                    subsection="reporting",
                    question_text="Describe the custom reports needed",
                    question_type=QuestionType.TEXTAREA,
                    required=True,
                    depends_on={"di_custom_reports": "Yes"},
                    placeholder="Describe the metrics, dimensions, and format needed",
                    order=5,
                ),
            ],
        ),
        SubsectionDefinition(
            key="data_feeds",
            title="Data Feeds",
            order=2,
            questions=[
                QuestionDefinition(
                    key="di_data_feed_required",
                    section="data_insights",
                    subsection="data_feeds",
                    question_text="Do you need automated data feeds to your systems?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No"],
                    required=True,
                    help_text="Data feeds push return data to your ERP, WMS, or analytics platform.",
                    order=1,
                ),
                QuestionDefinition(
                    key="di_feed_format",
                    section="data_insights",
                    subsection="data_feeds",
                    question_text="Preferred data feed format?",
                    question_type=QuestionType.SELECT,
                    options=["CSV (SFTP)", "JSON (API webhook)", "XML (SFTP)", "EDI"],
                    required=True,
                    depends_on={"di_data_feed_required": "Yes"},
                    order=2,
                    config_description="Configures data feed format in integration-service",
                ),
                QuestionDefinition(
                    key="di_feed_frequency",
                    section="data_insights",
                    subsection="data_feeds",
                    question_text="Data feed frequency?",
                    question_type=QuestionType.SELECT,
                    options=["Real-time (per event)", "Hourly", "Daily", "Weekly"],
                    required=True,
                    depends_on={"di_data_feed_required": "Yes"},
                    order=3,
                ),
                QuestionDefinition(
                    key="di_feed_endpoint",
                    section="data_insights",
                    subsection="data_feeds",
                    question_text="Target endpoint for data feeds",
                    question_type=QuestionType.TEXT,
                    required=True,
                    depends_on={"di_data_feed_required": "Yes"},
                    placeholder="e.g., sftp://ftp.client.com/returns or https://api.client.com/webhook",
                    order=4,
                ),
            ],
        ),
        SubsectionDefinition(
            key="dashboard_config",
            title="Dashboard",
            order=3,
            questions=[
                QuestionDefinition(
                    key="di_dashboard_access",
                    section="data_insights",
                    subsection="dashboard_config",
                    question_text="Should the client have access to a live dashboard?",
                    question_type=QuestionType.SELECT,
                    options=["Yes - ReBound dashboard", "Yes - embedded in client portal", "No"],
                    required=True,
                    order=1,
                    config_description="Configures dashboard access in analytics-service",
                ),
                QuestionDefinition(
                    key="di_dashboard_users",
                    section="data_insights",
                    subsection="dashboard_config",
                    question_text="How many dashboard users are needed?",
                    question_type=QuestionType.NUMBER,
                    required=True,
                    depends_on={"di_dashboard_access": ["Yes - ReBound dashboard", "Yes - embedded in client portal"]},
                    placeholder="e.g., 5",
                    order=2,
                ),
                QuestionDefinition(
                    key="di_dashboard_kpis",
                    section="data_insights",
                    subsection="dashboard_config",
                    question_text="Which KPIs should be displayed on the dashboard?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=["Return rate", "Processing time (SLA)", "Grading distribution", "Refund turnaround", "Volume trends", "Carrier performance", "Cost per return"],
                    required=True,
                    depends_on={"di_dashboard_access": ["Yes - ReBound dashboard", "Yes - embedded in client portal"]},
                    order=3,
                ),
            ],
        ),
        SubsectionDefinition(
            key="integrations",
            title="System Integrations",
            order=4,
            questions=[
                QuestionDefinition(
                    key="di_erp_integration",
                    section="data_insights",
                    subsection="integrations",
                    question_text="Do you need ERP integration?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No"],
                    required=True,
                    order=1,
                ),
                QuestionDefinition(
                    key="di_erp_system",
                    section="data_insights",
                    subsection="integrations",
                    question_text="Which ERP system?",
                    question_type=QuestionType.SELECT,
                    options=["SAP", "Oracle", "Microsoft Dynamics", "NetSuite", "Other"],
                    required=True,
                    depends_on={"di_erp_integration": "Yes"},
                    order=2,
                ),
                QuestionDefinition(
                    key="di_wms_integration",
                    section="data_insights",
                    subsection="integrations",
                    question_text="Do you need WMS (Warehouse Management System) integration?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No"],
                    required=True,
                    order=3,
                ),
                QuestionDefinition(
                    key="di_api_access",
                    section="data_insights",
                    subsection="integrations",
                    question_text="Do you need direct API access to return data?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No"],
                    required=True,
                    help_text="API access allows your engineering team to build custom integrations.",
                    order=4,
                    config_description="Configures API access in integration-service",
                ),
            ],
        ),
    ],
)
