from app.questions.types import QuestionDefinition, QuestionType, SectionDefinition, SubsectionDefinition

FIRST_MILE_SECTION = SectionDefinition(
    key="first_mile",
    title="First Mile",
    description="Define carrier lanes for European and overseas return routes.",
    order=2,
    subsections=[
        SubsectionDefinition(
            key="european_lanes",
            title="European Lanes",
            order=1,
            questions=[
                QuestionDefinition(
                    key="fm_european_lanes",
                    section="first_mile",
                    subsection="european_lanes",
                    question_text="Define European return lanes",
                    question_type=QuestionType.LANE_BUILDER,
                    required=True,
                    help_text="Each lane defines a return route: origin country, carrier, service type, first hub, last hub, and who pays.",
                    order=1,
                    target_service="c3",
                    config_description="Create European shipping templates in C3",
                    field_config={
                        "columns": [
                            {
                                "name": "country",
                                "label": "Country",
                                "type": "select",
                                "options": [
                                    "United Kingdom",
                                    "Germany",
                                    "France",
                                    "Netherlands",
                                    "Belgium",
                                    "Spain",
                                    "Italy",
                                    "Poland",
                                    "Sweden",
                                    "Denmark",
                                    "Norway",
                                    "Finland",
                                    "Austria",
                                    "Switzerland",
                                    "Ireland",
                                    "Portugal",
                                ],
                            },
                            {
                                "name": "carrier",
                                "label": "Carrier",
                                "type": "select",
                                "options": [
                                    "Royal Mail",
                                    "DHL",
                                    "DPD",
                                    "PostNL",
                                    "Hermes",
                                    "GLS",
                                    "UPS",
                                    "FedEx",
                                    "Colissimo",
                                    "Correos",
                                    "Poste Italiane",
                                    "InPost",
                                    "Evri",
                                ],
                            },
                            {
                                "name": "service",
                                "label": "Service",
                                "type": "select",
                                "options": ["Drop-off", "Pick-up", "Send-in"],
                            },
                            {
                                "name": "first_hub",
                                "label": "First Hub",
                                "type": "text",
                            },
                            {
                                "name": "last_hub",
                                "label": "Last Hub",
                                "type": "text",
                            },
                            {
                                "name": "consumer_paid",
                                "label": "Consumer Paid",
                                "type": "select",
                                "options": ["Yes", "No"],
                            },
                        ],
                        "min_rows": 1,
                        "max_rows": 50,
                    },
                ),
            ],
        ),
        SubsectionDefinition(
            key="overseas_lanes",
            title="Overseas Lanes",
            order=2,
            questions=[
                QuestionDefinition(
                    key="fm_overseas_lanes",
                    section="first_mile",
                    subsection="overseas_lanes",
                    question_text="Define overseas return lanes",
                    question_type=QuestionType.LANE_BUILDER,
                    help_text="Define return routes for non-European countries.",
                    order=1,
                    target_service="c3",
                    config_description="Create overseas shipping templates in C3",
                    field_config={
                        "columns": [
                            {
                                "name": "country",
                                "label": "Country",
                                "type": "select",
                                "options": [
                                    "United States",
                                    "Canada",
                                    "Australia",
                                    "China",
                                    "Japan",
                                    "South Korea",
                                    "India",
                                    "Brazil",
                                    "Mexico",
                                    "South Africa",
                                    "UAE",
                                    "Saudi Arabia",
                                    "Hong Kong",
                                    "Singapore",
                                    "New Zealand",
                                ],
                            },
                            {
                                "name": "carrier",
                                "label": "Carrier",
                                "type": "select",
                                "options": [
                                    "UPS",
                                    "FedEx",
                                    "DHL Express",
                                    "USPS",
                                    "Canada Post",
                                    "Australia Post",
                                    "Royal Mail",
                                    "Aramex",
                                    "SF Express",
                                ],
                            },
                            {
                                "name": "service",
                                "label": "Service",
                                "type": "select",
                                "options": ["Drop-off", "Pick-up", "Send-in"],
                            },
                            {
                                "name": "first_hub",
                                "label": "First Hub",
                                "type": "text",
                            },
                            {
                                "name": "last_hub",
                                "label": "Last Hub",
                                "type": "text",
                            },
                            {
                                "name": "consumer_paid",
                                "label": "Consumer Paid",
                                "type": "select",
                                "options": ["Yes", "No"],
                            },
                        ],
                        "min_rows": 0,
                        "max_rows": 50,
                    },
                ),
            ],
        ),
    ],
)
