from app.questions.types import QuestionDefinition, QuestionType, SectionDefinition, SubsectionDefinition

FIRST_MILE_SECTION = SectionDefinition(
    key="first_mile",
    title="First Mile",
    description="Configure carriers, label generation, and collection methods for return shipments.",
    order=2,
    subsections=[
        SubsectionDefinition(
            key="carrier_selection",
            title="Carrier Selection",
            order=1,
            questions=[
                QuestionDefinition(
                    key="fm_carriers",
                    section="first_mile",
                    subsection="carrier_selection",
                    question_text="Which carriers should be available for first-mile returns?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=["DHL", "DPD", "PostNL", "Royal Mail", "Hermes/Evri", "UPS", "FedEx", "GLS", "Colissimo", "Correos"],
                    required=True,
                    help_text="Select all carriers you want consumers to use for return shipments.",
                    order=1,
                    config_description="Configures carriers in first-mile-service",
                ),
                QuestionDefinition(
                    key="fm_carrier_priority",
                    section="first_mile",
                    subsection="carrier_selection",
                    question_text="Should carriers be prioritized by cost or speed?",
                    question_type=QuestionType.SELECT,
                    options=["Cheapest first", "Fastest first", "Consumer choice"],
                    required=True,
                    help_text="Determines the default carrier presented to consumers.",
                    order=2,
                    config_description="Configures carrier priority in first-mile-service",
                ),
                QuestionDefinition(
                    key="fm_carrier_per_country",
                    section="first_mile",
                    subsection="carrier_selection",
                    question_text="Do different countries require different carriers?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No - same carrier(s) everywhere"],
                    required=True,
                    help_text="Some carriers only operate in specific countries.",
                    order=3,
                ),
            ],
        ),
        SubsectionDefinition(
            key="label_generation",
            title="Label Generation",
            order=2,
            questions=[
                QuestionDefinition(
                    key="fm_label_type",
                    section="first_mile",
                    subsection="label_generation",
                    question_text="What type of return label should be generated?",
                    question_type=QuestionType.SELECT,
                    options=["Pre-paid label (included in parcel)", "Digital label (consumer prints)", "QR code (paperless)", "No label (B2B pickup)"],
                    required=True,
                    help_text="Digital labels and QR codes reduce environmental impact.",
                    order=1,
                    config_description="Configures label type in label-service",
                ),
                QuestionDefinition(
                    key="fm_label_format",
                    section="first_mile",
                    subsection="label_generation",
                    question_text="Preferred label format?",
                    question_type=QuestionType.SELECT,
                    options=["PDF (A4)", "PDF (4x6 thermal)", "ZPL (thermal printer)", "PNG"],
                    required=True,
                    depends_on={"fm_label_type": ["Pre-paid label (included in parcel)", "Digital label (consumer prints)"]},
                    help_text="Thermal formats (4x6, ZPL) are used for warehouse label printers.",
                    order=2,
                ),
                QuestionDefinition(
                    key="fm_label_branding",
                    section="first_mile",
                    subsection="label_generation",
                    question_text="Should the label include your brand logo?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No"],
                    required=False,
                    order=3,
                ),
            ],
        ),
        SubsectionDefinition(
            key="pickup_dropoff",
            title="Pickup & Drop-off",
            order=3,
            questions=[
                QuestionDefinition(
                    key="fm_collection_method",
                    section="first_mile",
                    subsection="pickup_dropoff",
                    question_text="How should return parcels be collected?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=["Drop-off at carrier point", "Home pickup", "Locker drop-off", "In-store return"],
                    required=True,
                    help_text="Select all collection methods to offer consumers.",
                    order=1,
                    config_description="Configures collection methods in first-mile-service",
                ),
                QuestionDefinition(
                    key="fm_home_pickup_carrier",
                    section="first_mile",
                    subsection="pickup_dropoff",
                    question_text="Which carrier handles home pickups?",
                    question_type=QuestionType.SELECT,
                    options=["DHL", "DPD", "UPS", "FedEx", "Local courier"],
                    required=True,
                    depends_on={"fm_collection_method": "Home pickup"},
                    help_text="Select the carrier responsible for home collection.",
                    order=2,
                ),
                QuestionDefinition(
                    key="fm_consolidation",
                    section="first_mile",
                    subsection="pickup_dropoff",
                    question_text="Should parcels be consolidated at a hub before forwarding to the warehouse?",
                    question_type=QuestionType.SELECT,
                    options=["Yes - use consolidation hub", "No - direct to warehouse"],
                    required=True,
                    help_text="Consolidation reduces shipping costs for international returns.",
                    order=3,
                    config_description="Configures consolidation in logistics-service",
                ),
            ],
        ),
        SubsectionDefinition(
            key="country_lanes",
            title="Country Lanes",
            order=4,
            questions=[
                QuestionDefinition(
                    key="fm_return_countries",
                    section="first_mile",
                    subsection="country_lanes",
                    question_text="From which countries do you accept returns?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=["United Kingdom", "Germany", "France", "Netherlands", "Belgium", "Spain", "Italy", "Sweden", "Denmark", "Norway", "Austria", "Switzerland", "Poland", "Ireland", "Portugal"],
                    required=True,
                    help_text="Select all countries where consumers can initiate returns.",
                    order=1,
                    config_description="Configures country lanes in first-mile-service",
                ),
                QuestionDefinition(
                    key="fm_warehouse_destination",
                    section="first_mile",
                    subsection="country_lanes",
                    question_text="What is the primary warehouse destination for returns?",
                    question_type=QuestionType.TEXT,
                    required=True,
                    help_text="Provide the city or warehouse code.",
                    placeholder="e.g., Tilburg, NL",
                    order=2,
                ),
                QuestionDefinition(
                    key="fm_multiple_warehouses",
                    section="first_mile",
                    subsection="country_lanes",
                    question_text="Do you have multiple warehouse destinations?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No"],
                    required=True,
                    order=3,
                ),
                QuestionDefinition(
                    key="fm_additional_warehouses",
                    section="first_mile",
                    subsection="country_lanes",
                    question_text="List additional warehouse destinations",
                    question_type=QuestionType.TEXTAREA,
                    required=True,
                    depends_on={"fm_multiple_warehouses": "Yes"},
                    placeholder="Warehouse name - City, Country (one per line)",
                    order=4,
                ),
            ],
        ),
    ],
)
