from app.questions.types import QuestionDefinition, QuestionType, SectionDefinition, SubsectionDefinition

GENERAL_SECTION = SectionDefinition(
    key="general",
    title="General",
    description="Basic client information and operating scope.",
    order=0,
    subsections=[
        # ── Subsection 1: Client Information ──────────────────────────
        SubsectionDefinition(
            key="client_info",
            title="Client Information",
            order=1,
            questions=[
                QuestionDefinition(
                    key="gen_client_name",
                    section="general",
                    subsection="client_info",
                    question_text="Client Name",
                    question_type=QuestionType.TEXT,
                    required=True,
                    order=1,
                    target_service="unicorn",
                    config_description="Configure client in Unicorn",
                ),
                QuestionDefinition(
                    key="gen_category",
                    section="general",
                    subsection="client_info",
                    question_text="Category",
                    question_type=QuestionType.MULTI_SELECT,
                    options=["Fashion", "Electronics", "Homeware", "Other"],
                    required=True,
                    order=2,
                ),
            ],
        ),
        # ── Subsection 2: Primary Contact ─────────────────────────────
        SubsectionDefinition(
            key="primary_contact",
            title="Primary Contact",
            order=2,
            questions=[
                QuestionDefinition(
                    key="gen_contact_name",
                    section="general",
                    subsection="primary_contact",
                    question_text="Name",
                    question_type=QuestionType.TEXT,
                    required=True,
                    order=1,
                ),
                QuestionDefinition(
                    key="gen_contact_email",
                    section="general",
                    subsection="primary_contact",
                    question_text="Email",
                    question_type=QuestionType.EMAIL,
                    required=True,
                    order=2,
                ),
                QuestionDefinition(
                    key="gen_contact_phone",
                    section="general",
                    subsection="primary_contact",
                    question_text="Phone Number",
                    question_type=QuestionType.TEXT,
                    required=True,
                    order=3,
                    placeholder="+44 20 1234 5678",
                ),
            ],
        ),
        # ── Subsection 3: Invoicing Entity ────────────────────────────
        SubsectionDefinition(
            key="invoicing_entity",
            title="Invoicing Entity",
            order=3,
            questions=[
                QuestionDefinition(
                    key="gen_inv_legal_entity",
                    section="general",
                    subsection="invoicing_entity",
                    question_text="Legal Entity Name",
                    question_type=QuestionType.TEXT,
                    required=True,
                    order=1,
                ),
                QuestionDefinition(
                    key="gen_inv_vat",
                    section="general",
                    subsection="invoicing_entity",
                    question_text="VAT",
                    question_type=QuestionType.TEXT,
                    required=True,
                    order=2,
                ),
                QuestionDefinition(
                    key="gen_inv_currency",
                    section="general",
                    subsection="invoicing_entity",
                    question_text="Currency",
                    question_type=QuestionType.SELECT,
                    options=[
                        "GBP", "EUR", "USD", "CAD", "AUD", "CHF",
                        "SEK", "NOK", "DKK", "PLN", "CZK", "HUF",
                        "RON", "JPY", "CNY", "INR", "BRL", "ZAR",
                        "AED", "SAR", "KRW", "MXN",
                    ],
                    required=True,
                    order=3,
                ),
                QuestionDefinition(
                    key="gen_inv_payment_term",
                    section="general",
                    subsection="invoicing_entity",
                    question_text="Payment Term",
                    question_type=QuestionType.SELECT,
                    options=["Net 15", "Net 30", "Net 45", "Net 60", "Net 90"],
                    required=True,
                    order=4,
                ),
                QuestionDefinition(
                    key="gen_inv_street",
                    section="general",
                    subsection="invoicing_entity",
                    question_text="Street Name",
                    question_type=QuestionType.TEXT,
                    required=True,
                    order=5,
                ),
                QuestionDefinition(
                    key="gen_inv_house_number",
                    section="general",
                    subsection="invoicing_entity",
                    question_text="House Number",
                    question_type=QuestionType.TEXT,
                    required=True,
                    order=6,
                ),
                QuestionDefinition(
                    key="gen_inv_postcode",
                    section="general",
                    subsection="invoicing_entity",
                    question_text="Postcode",
                    question_type=QuestionType.TEXT,
                    required=True,
                    order=7,
                ),
                QuestionDefinition(
                    key="gen_inv_city",
                    section="general",
                    subsection="invoicing_entity",
                    question_text="City",
                    question_type=QuestionType.TEXT,
                    required=True,
                    order=8,
                ),
                QuestionDefinition(
                    key="gen_inv_state",
                    section="general",
                    subsection="invoicing_entity",
                    question_text="State",
                    question_type=QuestionType.TEXT,
                    required=True,
                    order=9,
                ),
                QuestionDefinition(
                    key="gen_inv_country",
                    section="general",
                    subsection="invoicing_entity",
                    question_text="Country",
                    question_type=QuestionType.SELECT,
                    options=[
                        "United Kingdom", "Germany", "France", "Netherlands", "Belgium",
                        "Spain", "Italy", "Poland", "Sweden", "Denmark", "Norway",
                        "Finland", "Austria", "Switzerland", "Ireland", "Portugal",
                        "Czech Republic", "Romania", "Hungary", "United States",
                        "Canada", "Australia", "China", "Japan", "South Korea",
                        "India", "Brazil", "Mexico", "South Africa", "UAE",
                        "Saudi Arabia",
                    ],
                    required=True,
                    order=10,
                ),
            ],
        ),
    ],
)
