from app.questions.types import QuestionDefinition, QuestionType, SectionDefinition, SubsectionDefinition

GENERAL_SECTION = SectionDefinition(
    key="general",
    title="General",
    description="Basic client information and operating scope.",
    order=0,
    subsections=[
        SubsectionDefinition(
            key="client_info",
            title="Client Information",
            order=1,
            questions=[
                QuestionDefinition(
                    key="gen_client_name",
                    section="general",
                    subsection="client_info",
                    question_text="What is the client name?",
                    question_type=QuestionType.TEXT,
                    required=True,
                    order=1,
                    target_service="unicorn",
                    config_description="Configure the client in Unicorn",
                ),
                QuestionDefinition(
                    key="gen_operating_countries",
                    section="general",
                    subsection="client_info",
                    question_text="In which countries will the client operate?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=[
                        "United Kingdom",
                        "Germany",
                        "France",
                        "Netherlands",
                        "Belgium",
                        "Spain",
                        "Italy",
                        "Poland",
                        "Sweden",
                        "Denmark",
                        "Norway",
                        "Finland",
                        "Austria",
                        "Switzerland",
                        "Ireland",
                        "Portugal",
                        "Czech Republic",
                        "Romania",
                        "Hungary",
                        "United States",
                        "Canada",
                        "Australia",
                        "China",
                        "Japan",
                        "South Korea",
                        "India",
                        "Brazil",
                        "Mexico",
                        "South Africa",
                        "UAE",
                        "Saudi Arabia",
                    ],
                    required=True,
                    order=2,
                    target_service="unicorn",
                    config_description="Configure operating countries in Unicorn",
                ),
            ],
        ),
    ],
)
