from app.questions.types import QuestionDefinition, QuestionType, SectionDefinition, SubsectionDefinition

LAST_MILE_SECTION = SectionDefinition(
    key="last_mile",
    title="Last Mile",
    description="Configure outbound shipping, customs handling, and consolidation for processed returns.",
    order=4,
    subsections=[
        SubsectionDefinition(
            key="outbound_carriers",
            title="Outbound Carriers",
            order=1,
            questions=[
                QuestionDefinition(
                    key="lm_outbound_carriers",
                    section="last_mile",
                    subsection="outbound_carriers",
                    question_text="Which carriers should handle outbound shipments from the warehouse?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=["DHL", "DPD", "UPS", "FedEx", "PostNL", "GLS", "TNT", "Palletways"],
                    required=True,
                    help_text="Select carriers for shipping processed returns to their final destination.",
                    order=1,
                    config_description="Configures outbound carriers in last-mile-service",
                ),
                QuestionDefinition(
                    key="lm_shipment_type",
                    section="last_mile",
                    subsection="outbound_carriers",
                    question_text="What type of outbound shipments do you need?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=["Parcel (individual)", "Pallet (bulk)", "Container (full)", "Mixed"],
                    required=True,
                    order=2,
                ),
                QuestionDefinition(
                    key="lm_shipping_frequency",
                    section="last_mile",
                    subsection="outbound_carriers",
                    question_text="How often should outbound shipments be dispatched?",
                    question_type=QuestionType.SELECT,
                    options=["Daily", "Twice weekly", "Weekly", "On demand", "When container is full"],
                    required=True,
                    order=3,
                    config_description="Configures shipping schedule in last-mile-service",
                ),
            ],
        ),
        SubsectionDefinition(
            key="shipping_rules",
            title="Shipping Rules",
            order=2,
            questions=[
                QuestionDefinition(
                    key="lm_destination_type",
                    section="last_mile",
                    subsection="shipping_rules",
                    question_text="Where should processed returns be shipped?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=["Back to client warehouse", "Outlet/liquidation", "Recycling partner", "Charity", "Destruction"],
                    required=True,
                    help_text="Different grades may go to different destinations.",
                    order=1,
                    config_description="Configures destinations in destination_per_sorting_type",
                ),
                QuestionDefinition(
                    key="lm_grade_routing",
                    section="last_mile",
                    subsection="shipping_rules",
                    question_text="Should different item grades be routed to different destinations?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No - all to same destination"],
                    required=True,
                    order=2,
                ),
                QuestionDefinition(
                    key="lm_grade_a_destination",
                    section="last_mile",
                    subsection="shipping_rules",
                    question_text="Destination for A-grade (resellable) items?",
                    question_type=QuestionType.TEXT,
                    required=True,
                    depends_on={"lm_grade_routing": "Yes"},
                    placeholder="e.g., Client main warehouse, Berlin",
                    order=3,
                ),
                QuestionDefinition(
                    key="lm_grade_b_destination",
                    section="last_mile",
                    subsection="shipping_rules",
                    question_text="Destination for B-grade (discounted) items?",
                    question_type=QuestionType.TEXT,
                    required=True,
                    depends_on={"lm_grade_routing": "Yes"},
                    placeholder="e.g., Outlet partner, Amsterdam",
                    order=4,
                ),
                QuestionDefinition(
                    key="lm_grade_c_destination",
                    section="last_mile",
                    subsection="shipping_rules",
                    question_text="Destination for C-grade (non-resellable) items?",
                    question_type=QuestionType.TEXT,
                    required=True,
                    depends_on={"lm_grade_routing": "Yes"},
                    placeholder="e.g., Recycling partner or destruction",
                    order=5,
                ),
            ],
        ),
        SubsectionDefinition(
            key="customs_duties",
            title="Customs & Duties",
            order=3,
            questions=[
                QuestionDefinition(
                    key="lm_customs_required",
                    section="last_mile",
                    subsection="customs_duties",
                    question_text="Are customs declarations required for outbound shipments?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No"],
                    required=True,
                    help_text="Required for cross-border shipments outside the EU.",
                    order=1,
                ),
                QuestionDefinition(
                    key="lm_customs_broker",
                    section="last_mile",
                    subsection="customs_duties",
                    question_text="Who handles customs brokerage?",
                    question_type=QuestionType.SELECT,
                    options=["ReBound", "Client", "Third-party broker"],
                    required=True,
                    depends_on={"lm_customs_required": "Yes"},
                    order=2,
                ),
                QuestionDefinition(
                    key="lm_hs_codes",
                    section="last_mile",
                    subsection="customs_duties",
                    question_text="Will you provide HS codes for all products?",
                    question_type=QuestionType.SELECT,
                    options=["Yes - in product feed", "No - ReBound to classify"],
                    required=True,
                    depends_on={"lm_customs_required": "Yes"},
                    order=3,
                ),
            ],
        ),
        SubsectionDefinition(
            key="consolidation",
            title="Consolidation",
            order=4,
            questions=[
                QuestionDefinition(
                    key="lm_consolidation_required",
                    section="last_mile",
                    subsection="consolidation",
                    question_text="Should returns be consolidated before outbound shipping?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No"],
                    required=True,
                    help_text="Consolidation groups items for bulk shipment to reduce costs.",
                    order=1,
                    config_description="Configures consolidation in logistics-service",
                ),
                QuestionDefinition(
                    key="lm_consolidation_trigger",
                    section="last_mile",
                    subsection="consolidation",
                    question_text="What triggers a consolidation shipment?",
                    question_type=QuestionType.SELECT,
                    options=["Volume threshold (number of items)", "Weight threshold", "Time-based (weekly)", "Manual trigger"],
                    required=True,
                    depends_on={"lm_consolidation_required": "Yes"},
                    order=2,
                ),
                QuestionDefinition(
                    key="lm_consolidation_threshold",
                    section="last_mile",
                    subsection="consolidation",
                    question_text="Consolidation threshold value",
                    question_type=QuestionType.NUMBER,
                    required=True,
                    depends_on={"lm_consolidation_trigger": ["Volume threshold (number of items)", "Weight threshold"]},
                    placeholder="e.g., 500 (items) or 200 (kg)",
                    order=3,
                ),
            ],
        ),
    ],
)
