from app.questions.types import QuestionDefinition, QuestionType, SectionDefinition, SubsectionDefinition

LAST_MILE_SECTION = SectionDefinition(
    key="last_mile",
    title="Last Mile",
    description="Configure destination addresses, logistics requirements, and customs clearance for outbound shipments.",
    order=4,
    subsections=[
        SubsectionDefinition(
            key="destination",
            title="Destination Address",
            order=1,
            questions=[
                QuestionDefinition(
                    key="lm_destination_address",
                    section="last_mile",
                    subsection="destination",
                    question_text="Provide the destination address details",
                    question_type=QuestionType.ADDRESS_FORM,
                    required=True,
                    help_text="Enter the full delivery address for this destination.",
                    order=1,
                    config_description="Store destination address for last-mile routing",
                    field_config={
                        "fields": [
                            {"name": "location_name", "label": "Location Name", "type": "text", "required": True, "placeholder": "e.g. Tilburg Warehouse"},
                            {"name": "street", "label": "Street", "type": "text", "required": True},
                            {"name": "house_number", "label": "House Number", "type": "text", "required": True},
                            {"name": "suffix", "label": "Address Suffix", "type": "text", "required": False},
                            {"name": "unit", "label": "Unit / Apartment", "type": "text", "required": False},
                            {"name": "postal_code", "label": "Postal Code", "type": "text", "required": True},
                            {"name": "suburb", "label": "Suburb / District", "type": "text", "required": False},
                            {"name": "city", "label": "City", "type": "text", "required": True},
                            {"name": "state", "label": "Province / State", "type": "text", "required": False},
                            {"name": "country", "label": "Country", "type": "text", "required": True},
                            {"name": "phone", "label": "Phone Number", "type": "text", "required": True},
                            {"name": "contact_details", "label": "Contact Person & Details", "type": "text", "required": False},
                            {"name": "remarks", "label": "Delivery Remarks", "type": "text", "required": False},
                        ]
                    },
                ),
            ],
        ),
        SubsectionDefinition(
            key="logistics",
            title="Logistics & Delivery",
            order=2,
            questions=[
                QuestionDefinition(
                    key="lm_unloading_equipment",
                    section="last_mile",
                    subsection="logistics",
                    question_text="What unloading equipment is available at the destination?",
                    question_type=QuestionType.TEXT,
                    placeholder="e.g. Dock leveler, Forklift, Pallet jack",
                    order=1,
                    config_description="Record dock/handling equipment for carrier planning",
                ),
                QuestionDefinition(
                    key="lm_unloading_restrictions",
                    section="last_mile",
                    subsection="logistics",
                    question_text="Are there delivery equipment restrictions?",
                    question_type=QuestionType.TEXT,
                    placeholder="e.g. No articulated vehicles, max 7.5t",
                    order=2,
                    config_description="Capture restrictions impacting carrier or vehicle",
                ),
                QuestionDefinition(
                    key="lm_booking_requirements",
                    section="last_mile",
                    subsection="logistics",
                    question_text="What booking procedure is required?",
                    question_type=QuestionType.TEXTAREA,
                    placeholder="Describe appointment scheduling process",
                    order=3,
                    config_description="Define appointment scheduling process",
                ),
                QuestionDefinition(
                    key="lm_prealert_requirements",
                    section="last_mile",
                    subsection="logistics",
                    question_text="What pre-alert delivery requirements apply?",
                    question_type=QuestionType.TEXTAREA,
                    placeholder="Describe advance notification rules",
                    order=4,
                    config_description="Define advance notification rules",
                ),
                QuestionDefinition(
                    key="lm_delivery_timeslots",
                    section="last_mile",
                    subsection="logistics",
                    question_text="Are there specific delivery timeslots?",
                    question_type=QuestionType.TEXT,
                    placeholder="e.g. Mon-Fri 08:00-16:00",
                    order=5,
                    config_description="Store allowed delivery windows",
                ),
                QuestionDefinition(
                    key="lm_unloading_responsibility",
                    section="last_mile",
                    subsection="logistics",
                    question_text="Who unloads the shipment?",
                    question_type=QuestionType.SELECT,
                    options=["Driver", "Warehouse staff"],
                    order=6,
                    config_description="Define operational unloading responsibility",
                ),
                QuestionDefinition(
                    key="lm_driver_monitoring",
                    section="last_mile",
                    subsection="logistics",
                    question_text="Can the driver monitor unloading?",
                    question_type=QuestionType.BOOLEAN,
                    order=7,
                    config_description="Define visibility/escort rule during unloading",
                ),
            ],
        ),
        SubsectionDefinition(
            key="customs_clearance",
            title="Customs Clearance",
            order=3,
            questions=[
                QuestionDefinition(
                    key="lm_container_type",
                    section="last_mile",
                    subsection="customs_clearance",
                    question_text="Select transport container type per customs lane",
                    question_type=QuestionType.SELECT,
                    options=["Pallet", "Cage", "Box", "Bag", "Mixed"],
                    depends_on={"ri_customs_lanes": True},
                    order=1,
                    config_description="Store container type per lane for customs routing",
                ),
                QuestionDefinition(
                    key="lm_transport_supplier",
                    section="last_mile",
                    subsection="customs_clearance",
                    question_text="Name of transport supplier",
                    question_type=QuestionType.TEXT,
                    depends_on={"ri_customs_lanes": True},
                    placeholder="e.g. DHL Freight",
                    order=2,
                    config_description="Store carrier responsible for customs movement",
                ),
                QuestionDefinition(
                    key="lm_customs_data_integration",
                    section="last_mile",
                    subsection="customs_clearance",
                    question_text="Will essential customs data be provided via client integration?",
                    question_type=QuestionType.BOOLEAN,
                    required=True,
                    depends_on={"ri_customs_lanes": True},
                    help_text="If No, manual customs data handling will be required.",
                    order=3,
                    config_description="Configure customs data ingestion or manual handling",
                ),
                QuestionDefinition(
                    key="lm_export_clearance",
                    section="last_mile",
                    subsection="customs_clearance",
                    question_text="Should ReBound perform export clearance?",
                    question_type=QuestionType.BOOLEAN,
                    depends_on={"ri_customs_lanes": True},
                    help_text="Required documentation must be signed at least 1 week before go-live.",
                    order=4,
                    config_description="Enable ReBound export clearance workflow",
                ),
                QuestionDefinition(
                    key="lm_import_clearance",
                    section="last_mile",
                    subsection="customs_clearance",
                    question_text="Should ReBound perform import clearance?",
                    question_type=QuestionType.BOOLEAN,
                    depends_on={"ri_customs_lanes": True},
                    order=5,
                    config_description="Enable ReBound import clearance workflow",
                ),
                QuestionDefinition(
                    key="lm_import_procedure",
                    section="last_mile",
                    subsection="customs_clearance",
                    question_text="Which import procedure is used?",
                    question_type=QuestionType.SELECT,
                    options=["Home Use", "Bonded", "Returned Goods Relief (RGR)"],
                    required=True,
                    depends_on={"ri_customs_lanes": True},
                    order=6,
                    config_description="Configure customs declaration logic and duty handling",
                ),
                QuestionDefinition(
                    key="lm_niru_details",
                    section="last_mile",
                    subsection="customs_clearance",
                    question_text="Provide NIRU number, issue date, and expiry date",
                    question_type=QuestionType.TEXT,
                    depends_on={"lm_import_procedure": "Returned Goods Relief (RGR)"},
                    placeholder="NIRU number, issue date, expiry date",
                    order=7,
                    config_description="Store NIRU metadata for RGR validation",
                ),
                QuestionDefinition(
                    key="lm_deferment_account",
                    section="last_mile",
                    subsection="customs_clearance",
                    question_text="Provide deferment account number",
                    question_type=QuestionType.TEXT,
                    depends_on={"lm_import_procedure": "Home Use"},
                    placeholder="e.g. 1234567",
                    order=8,
                    config_description="Configure duty deferment billing",
                ),
                QuestionDefinition(
                    key="lm_importer_of_record",
                    section="last_mile",
                    subsection="customs_clearance",
                    question_text="Who acts as Importer of Record (IOR)?",
                    question_type=QuestionType.TEXT,
                    required=True,
                    depends_on={"ri_customs_lanes": True},
                    placeholder="Entity name",
                    order=9,
                    config_description="Configure declaration ownership and liability",
                ),
                QuestionDefinition(
                    key="lm_ior_registrations",
                    section="last_mile",
                    subsection="customs_clearance",
                    question_text="Does the IOR have valid EORI/VAT/Tax registrations?",
                    question_type=QuestionType.BOOLEAN,
                    depends_on={"ri_customs_lanes": True},
                    order=10,
                    config_description="Validate customs eligibility",
                ),
                QuestionDefinition(
                    key="lm_ior_entity_details",
                    section="last_mile",
                    subsection="customs_clearance",
                    question_text="Provide IOR entity name, address, VAT/EORI for declarations",
                    question_type=QuestionType.TEXTAREA,
                    depends_on={"ri_customs_lanes": True},
                    placeholder="Entity name, registered address, VAT number, EORI number",
                    order=11,
                    config_description="Store declaration master data",
                ),
                QuestionDefinition(
                    key="lm_customs_poa_signed",
                    section="last_mile",
                    subsection="customs_clearance",
                    question_text="Is Power of Attorney / customs authorization signed?",
                    question_type=QuestionType.BOOLEAN,
                    required=True,
                    depends_on={"ri_customs_lanes": True},
                    order=12,
                    config_description="Enable broker/customs representation",
                ),
            ],
        ),
        SubsectionDefinition(
            key="customs_operations",
            title="Customs Operations",
            order=4,
            questions=[
                QuestionDefinition(
                    key="lm_t1_closure_broker",
                    section="last_mile",
                    subsection="customs_operations",
                    question_text="Which broker handles T1 closure?",
                    question_type=QuestionType.TEXT,
                    depends_on={"lm_import_procedure": "Bonded"},
                    order=1,
                    config_description="Configure bonded transit closure responsibility",
                ),
                QuestionDefinition(
                    key="lm_bonded_arrival_instructions",
                    section="last_mile",
                    subsection="customs_operations",
                    question_text="Instructions when driver arrives with bonded goods",
                    question_type=QuestionType.TEXTAREA,
                    depends_on={"lm_import_procedure": "Bonded"},
                    order=2,
                    config_description="Store operational SOP for bonded intake",
                ),
                QuestionDefinition(
                    key="lm_bonded_storage_duration",
                    section="last_mile",
                    subsection="customs_operations",
                    question_text="Average bonded storage duration",
                    question_type=QuestionType.TEXT,
                    depends_on={"lm_import_procedure": "Bonded"},
                    placeholder="e.g. 30 days",
                    order=3,
                    config_description="Inform compliance and warehouse planning",
                ),
                QuestionDefinition(
                    key="lm_bonded_auth_code",
                    section="last_mile",
                    subsection="customs_operations",
                    question_text="Bonded warehouse authorization code",
                    question_type=QuestionType.TEXT,
                    depends_on={"lm_import_procedure": "Bonded"},
                    order=4,
                    config_description="Store regulatory approval reference",
                ),
                QuestionDefinition(
                    key="lm_britannia_booklet",
                    section="last_mile",
                    subsection="customs_operations",
                    question_text="Has the Britannia Bureau booklet been provided?",
                    question_type=QuestionType.BOOLEAN,
                    depends_on={"lm_import_procedure": "Bonded"},
                    help_text="Required for UK bonded warehouse operations only.",
                    order=5,
                    config_description="Confirm UK bonded compliance documentation",
                ),
                QuestionDefinition(
                    key="lm_exporter_of_record",
                    section="last_mile",
                    subsection="customs_operations",
                    question_text="Who acts as Exporter of Record?",
                    question_type=QuestionType.TEXT,
                    depends_on={"ri_customs_lanes": True},
                    placeholder="Entity name",
                    order=6,
                    config_description="Determine export paperwork and liability",
                ),
                QuestionDefinition(
                    key="lm_ups_account_number",
                    section="last_mile",
                    subsection="customs_operations",
                    question_text="Provide UPS account number for duties/taxes",
                    question_type=QuestionType.TEXT,
                    depends_on={"ri_customs_lanes": True},
                    order=7,
                    config_description="Configure UPS billing for customs charges",
                ),
                QuestionDefinition(
                    key="lm_ups_account_address",
                    section="last_mile",
                    subsection="customs_operations",
                    question_text="Address linked to UPS account",
                    question_type=QuestionType.TEXT,
                    depends_on={"lm_ups_account_number": {"$not_empty": True}},
                    order=8,
                    config_description="Validate billing setup",
                ),
                QuestionDefinition(
                    key="lm_ups_billing_role",
                    section="last_mile",
                    subsection="customs_operations",
                    question_text="Confirm importer role for UPS billing",
                    question_type=QuestionType.SELECT,
                    options=["Receiver", "Third-party"],
                    depends_on={"lm_ups_account_number": {"$not_empty": True}},
                    order=9,
                    config_description="Configure UPS duty/tax billing model",
                ),
                QuestionDefinition(
                    key="lm_export_broker_details",
                    section="last_mile",
                    subsection="customs_operations",
                    question_text="Export broker details and contact info",
                    question_type=QuestionType.TEXTAREA,
                    depends_on={"ri_customs_lanes": True},
                    order=10,
                    config_description="Store broker contact and responsibility",
                ),
                QuestionDefinition(
                    key="lm_import_broker_details",
                    section="last_mile",
                    subsection="customs_operations",
                    question_text="Import broker details and contact info",
                    question_type=QuestionType.TEXTAREA,
                    depends_on={"ri_customs_lanes": True},
                    order=11,
                    config_description="Store broker contact and responsibility",
                ),
                QuestionDefinition(
                    key="lm_broker_standard_fields",
                    section="last_mile",
                    subsection="customs_operations",
                    question_text="Can the broker handle standard customs data fields?",
                    question_type=QuestionType.BOOLEAN,
                    depends_on={"ri_customs_lanes": True},
                    order=12,
                    config_description="Validate compatibility with ReBound master data",
                ),
                QuestionDefinition(
                    key="lm_broker_extra_data",
                    section="last_mile",
                    subsection="customs_operations",
                    question_text="Does the broker require extra customs data?",
                    question_type=QuestionType.BOOLEAN,
                    depends_on={"ri_customs_lanes": True},
                    order=13,
                    config_description="Client must supply additional data outside ReBound standard",
                ),
                QuestionDefinition(
                    key="lm_customs_processing_mode",
                    section="last_mile",
                    subsection="customs_operations",
                    question_text="Use quarantine task list or PIM for customs processing?",
                    question_type=QuestionType.SELECT,
                    options=["PIM", "Quarantine Task List"],
                    depends_on={"ri_customs_lanes": True},
                    help_text="PIM is default. Task list recommended for <100 parcels/month.",
                    order=14,
                    config_description="Configure customs handling workflow",
                ),
            ],
        ),
    ],
)
