from app.questions.types import QuestionDefinition, QuestionType, SectionDefinition, SubsectionDefinition

NOTIFICATIONS_TRACKING_SECTION = SectionDefinition(
    key="notifications_tracking",
    title="Notifications & Tracking",
    description="Configure consumer email notifications, tracking push updates, and refund trigger webhooks.",
    order=5,
    subsections=[
        # ── Consumer Notifications ─────────────────────────────────────
        SubsectionDefinition(
            key="consumer_notifications",
            title="Consumer Notifications",
            order=1,
            questions=[
                QuestionDefinition(
                    key="nt_email_milestone",
                    section="notifications_tracking",
                    subsection="consumer_notifications",
                    question_text="At which milestone should the consumer receive an email?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=[
                        "Return registered",
                        "Label generated",
                        "Parcel received at warehouse",
                        "Processing started",
                        "Grading complete",
                        "Refund initiated",
                        "Refund completed",
                    ],
                    required=True,
                    order=1,
                    target_service="pigeon",
                    config_description="Configure email triggers in Pigeon notification templates",
                ),
                QuestionDefinition(
                    key="nt_email_logo",
                    section="notifications_tracking",
                    subsection="consumer_notifications",
                    question_text="Should the client logo appear in notification emails?",
                    question_type=QuestionType.BOOLEAN,
                    required=True,
                    order=2,
                    target_service="pigeon",
                    config_description="Toggle logo display in Pigeon email template",
                ),
                QuestionDefinition(
                    key="nt_email_template_mode",
                    section="notifications_tracking",
                    subsection="consumer_notifications",
                    question_text="Email template mode",
                    question_type=QuestionType.SELECT,
                    options=["ReBound default template", "Client brand template", "Client brand colors/logo only"],
                    required=True,
                    order=3,
                    target_service="pigeon",
                    config_description="Select template strategy in Pigeon",
                ),
                QuestionDefinition(
                    key="nt_email_multilingual",
                    section="notifications_tracking",
                    subsection="consumer_notifications",
                    question_text="Are multilingual email templates required?",
                    question_type=QuestionType.BOOLEAN,
                    required=True,
                    help_text="If yes, templates will be generated per supported language.",
                    order=4,
                    target_service="pigeon",
                    config_description="Enable multilingual template set in Pigeon",
                ),
                QuestionDefinition(
                    key="nt_sender_email",
                    section="notifications_tracking",
                    subsection="consumer_notifications",
                    question_text="Sender email address for consumer notifications",
                    question_type=QuestionType.EMAIL,
                    required=True,
                    placeholder="returns@yourstore.com",
                    order=5,
                    target_service="pigeon",
                    config_description="Set sender address in Pigeon outbound config",
                ),
            ],
        ),
        # ── Tracking Push ──────────────────────────────────────────────
        SubsectionDefinition(
            key="tracking_push",
            title="Tracking Push",
            order=2,
            questions=[
                QuestionDefinition(
                    key="nt_tracking_milestones",
                    section="notifications_tracking",
                    subsection="tracking_push",
                    question_text="At which milestones should tracking pushes be sent?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=[
                        "Return registered",
                        "Label generated",
                        "Parcel in transit",
                        "Parcel received at warehouse",
                        "Processing started",
                        "Grading complete",
                        "Refund initiated",
                        "Refund completed",
                    ],
                    required=True,
                    order=1,
                    target_service="pigeon",
                    config_description="Configure tracking push triggers in Pigeon",
                ),
                QuestionDefinition(
                    key="nt_tracking_delivery_method",
                    section="notifications_tracking",
                    subsection="tracking_push",
                    question_text="Tracking push delivery method",
                    question_type=QuestionType.SELECT,
                    options=["API (webhook)", "SFTP"],
                    required=True,
                    order=2,
                    target_service="pigeon",
                    config_description="Configure delivery channel in Pigeon tracking config",
                ),
                QuestionDefinition(
                    key="nt_tracking_api_url",
                    section="notifications_tracking",
                    subsection="tracking_push",
                    question_text="Tracking push API endpoint URL",
                    question_type=QuestionType.TEXT,
                    depends_on={"nt_tracking_delivery_method": "API (webhook)"},
                    placeholder="https://api.client.com/tracking-webhook",
                    order=3,
                    target_service="pigeon",
                    config_description="Set webhook URL in Pigeon tracking push config",
                ),
                QuestionDefinition(
                    key="nt_tracking_api_headers",
                    section="notifications_tracking",
                    subsection="tracking_push",
                    question_text="Tracking push API headers",
                    question_type=QuestionType.KEY_VALUE,
                    depends_on={"nt_tracking_delivery_method": "API (webhook)"},
                    help_text="Add custom headers for the tracking webhook (e.g. Authorization, X-API-Key).",
                    order=4,
                    target_service="pigeon",
                    config_description="Set API headers in Pigeon tracking push config",
                    field_config={
                        "key_label": "Header Name",
                        "value_label": "Header Value",
                        "key_placeholder": "e.g. Authorization",
                        "value_placeholder": "e.g. Bearer token123",
                        "max_rows": 10,
                    },
                ),
                QuestionDefinition(
                    key="nt_tracking_sftp",
                    section="notifications_tracking",
                    subsection="tracking_push",
                    question_text="Tracking push SFTP connection details",
                    question_type=QuestionType.OBJECT,
                    depends_on={"nt_tracking_delivery_method": "SFTP"},
                    order=5,
                    target_service="pigeon",
                    config_description="Set SFTP connection in Pigeon tracking push config",
                    field_config={
                        "fields": [
                            {"key": "host", "label": "SFTP Host", "type": "text", "placeholder": "sftp.client.com", "required": True},
                            {"key": "port", "label": "Port", "type": "number", "placeholder": "22", "required": True},
                            {"key": "username", "label": "Username", "type": "text", "placeholder": "sftp_user", "required": True},
                            {"key": "password", "label": "Password", "type": "text", "placeholder": "••••••••", "required": True},
                            {"key": "path", "label": "Remote Path", "type": "text", "placeholder": "/uploads/tracking/", "required": False},
                        ]
                    },
                ),
            ],
        ),
        # ── Refund Trigger ─────────────────────────────────────────────
        SubsectionDefinition(
            key="refund_trigger",
            title="Refund Trigger",
            order=3,
            questions=[
                QuestionDefinition(
                    key="nt_refund_milestone",
                    section="notifications_tracking",
                    subsection="refund_trigger",
                    question_text="At which milestone should refund be triggered?",
                    question_type=QuestionType.SELECT,
                    options=["Parcel received", "Processing complete", "Grading complete", "Manual trigger only"],
                    required=True,
                    depends_on={"ri_refund_trigger": True},
                    order=1,
                    target_service="pigeon",
                    config_description="Configure refund trigger milestone in Pigeon",
                ),
                QuestionDefinition(
                    key="nt_refund_unexpected_items",
                    section="notifications_tracking",
                    subsection="refund_trigger",
                    question_text="How should unexpected items be handled for refund?",
                    question_type=QuestionType.SELECT,
                    options=["Include in refund", "Exclude from refund", "Flag for manual review"],
                    depends_on={"ri_refund_trigger": True},
                    order=2,
                    target_service="pigeon",
                    config_description="Configure unexpected item handling in refund logic",
                ),
                QuestionDefinition(
                    key="nt_refund_delivery_method",
                    section="notifications_tracking",
                    subsection="refund_trigger",
                    question_text="Refund trigger delivery method",
                    question_type=QuestionType.SELECT,
                    options=["API (webhook)", "SFTP"],
                    required=True,
                    depends_on={"ri_refund_trigger": True},
                    order=3,
                    target_service="pigeon",
                    config_description="Configure refund trigger delivery channel in Pigeon",
                ),
                QuestionDefinition(
                    key="nt_refund_api_url",
                    section="notifications_tracking",
                    subsection="refund_trigger",
                    question_text="Refund trigger API endpoint URL",
                    question_type=QuestionType.TEXT,
                    depends_on={"nt_refund_delivery_method": "API (webhook)"},
                    placeholder="https://api.client.com/refund-webhook",
                    order=4,
                    target_service="pigeon",
                    config_description="Set refund webhook URL in Pigeon",
                ),
                QuestionDefinition(
                    key="nt_refund_api_auth",
                    section="notifications_tracking",
                    subsection="refund_trigger",
                    question_text="Refund API authentication type",
                    question_type=QuestionType.SELECT,
                    options=["Bearer token", "Basic auth", "API key header", "No auth"],
                    depends_on={"nt_refund_delivery_method": "API (webhook)"},
                    order=5,
                    target_service="pigeon",
                    config_description="Set auth method for refund webhook in Pigeon",
                ),
                QuestionDefinition(
                    key="nt_refund_api_headers",
                    section="notifications_tracking",
                    subsection="refund_trigger",
                    question_text="Refund trigger API headers",
                    question_type=QuestionType.KEY_VALUE,
                    depends_on={"nt_refund_delivery_method": "API (webhook)"},
                    help_text="Add custom headers for the refund webhook.",
                    order=6,
                    target_service="pigeon",
                    config_description="Set API headers for refund webhook in Pigeon",
                    field_config={
                        "key_label": "Header Name",
                        "value_label": "Header Value",
                        "key_placeholder": "e.g. X-API-Key",
                        "value_placeholder": "e.g. abc123",
                        "max_rows": 10,
                    },
                ),
                QuestionDefinition(
                    key="nt_refund_sftp",
                    section="notifications_tracking",
                    subsection="refund_trigger",
                    question_text="Refund trigger SFTP connection details",
                    question_type=QuestionType.OBJECT,
                    depends_on={"nt_refund_delivery_method": "SFTP"},
                    order=7,
                    target_service="pigeon",
                    config_description="Set SFTP connection for refund trigger in Pigeon",
                    field_config={
                        "fields": [
                            {"key": "host", "label": "SFTP Host", "type": "text", "placeholder": "sftp.client.com", "required": True},
                            {"key": "port", "label": "Port", "type": "number", "placeholder": "22", "required": True},
                            {"key": "username", "label": "Username", "type": "text", "placeholder": "sftp_user", "required": True},
                            {"key": "password", "label": "Password", "type": "text", "placeholder": "••••••••", "required": True},
                            {"key": "path", "label": "Remote Path", "type": "text", "placeholder": "/uploads/refunds/", "required": False},
                        ]
                    },
                ),
            ],
        ),
    ],
)
