from app.questions.types import QuestionDefinition, QuestionType, SectionDefinition, SubsectionDefinition

NOTIFICATIONS_SECTION = SectionDefinition(
    key="notifications_messaging",
    title="Notifications & Messaging",
    description="Configure email notifications, tracking updates, and consumer communication preferences.",
    order=5,
    subsections=[
        SubsectionDefinition(
            key="email_templates",
            title="Email Templates",
            order=1,
            questions=[
                QuestionDefinition(
                    key="nm_email_provider",
                    section="notifications_messaging",
                    subsection="email_templates",
                    question_text="Which email service should send notifications?",
                    question_type=QuestionType.SELECT,
                    options=["ReBound email service", "Client email service (via API)", "Third-party (SendGrid, Mailgun, etc.)"],
                    required=True,
                    help_text="Determines which system sends transactional emails to consumers.",
                    order=1,
                    config_description="Configures email provider in notification-service",
                ),
                QuestionDefinition(
                    key="nm_sender_email",
                    section="notifications_messaging",
                    subsection="email_templates",
                    question_text="What sender email address should be used?",
                    question_type=QuestionType.EMAIL,
                    required=True,
                    placeholder="returns@yourstore.com",
                    order=2,
                ),
                QuestionDefinition(
                    key="nm_email_branding",
                    section="notifications_messaging",
                    subsection="email_templates",
                    question_text="Should emails use your brand template?",
                    question_type=QuestionType.SELECT,
                    options=["Yes - provide brand template", "Yes - use brand colors/logo only", "No - use ReBound default"],
                    required=True,
                    order=3,
                ),
                QuestionDefinition(
                    key="nm_email_languages",
                    section="notifications_messaging",
                    subsection="email_templates",
                    question_text="Which languages should email notifications support?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=["English", "German", "French", "Dutch", "Spanish", "Italian", "Portuguese", "Swedish"],
                    required=True,
                    order=4,
                ),
            ],
        ),
        SubsectionDefinition(
            key="status_updates",
            title="Status Updates",
            order=2,
            questions=[
                QuestionDefinition(
                    key="nm_notification_triggers",
                    section="notifications_messaging",
                    subsection="status_updates",
                    question_text="At which stages should consumers receive notifications?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=[
                        "Return registered",
                        "Label generated",
                        "Parcel received at warehouse",
                        "Processing started",
                        "Grading complete",
                        "Refund initiated",
                        "Refund completed",
                        "Exchange shipped",
                    ],
                    required=True,
                    help_text="Select all stages where consumers should be notified.",
                    order=1,
                    config_description="Configures notification triggers in notification-service",
                ),
                QuestionDefinition(
                    key="nm_sms_enabled",
                    section="notifications_messaging",
                    subsection="status_updates",
                    question_text="Should SMS notifications be enabled?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No"],
                    required=True,
                    order=2,
                ),
                QuestionDefinition(
                    key="nm_push_enabled",
                    section="notifications_messaging",
                    subsection="status_updates",
                    question_text="Should push notifications be enabled (if app exists)?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No", "N/A - no app"],
                    required=True,
                    order=3,
                ),
            ],
        ),
        SubsectionDefinition(
            key="tracking_page",
            title="Tracking Page",
            order=3,
            questions=[
                QuestionDefinition(
                    key="nm_tracking_page",
                    section="notifications_messaging",
                    subsection="tracking_page",
                    question_text="Should a branded tracking page be provided to consumers?",
                    question_type=QuestionType.SELECT,
                    options=["Yes - ReBound hosted", "Yes - embedded in client site", "No - carrier tracking only"],
                    required=True,
                    help_text="A tracking page shows return status in a branded experience.",
                    order=1,
                    config_description="Configures tracking page in tracking-service",
                ),
                QuestionDefinition(
                    key="nm_tracking_statuses",
                    section="notifications_messaging",
                    subsection="tracking_page",
                    question_text="Which statuses should appear on the tracking page?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=["Return created", "In transit", "Received", "Processing", "Graded", "Refund pending", "Refund complete"],
                    required=True,
                    depends_on={"nm_tracking_page": ["Yes - ReBound hosted", "Yes - embedded in client site"]},
                    order=2,
                ),
                QuestionDefinition(
                    key="nm_tracking_eta",
                    section="notifications_messaging",
                    subsection="tracking_page",
                    question_text="Show estimated refund timeline on tracking page?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No"],
                    required=False,
                    depends_on={"nm_tracking_page": ["Yes - ReBound hosted", "Yes - embedded in client site"]},
                    order=3,
                ),
            ],
        ),
    ],
)
