from app.questions.types import QuestionDefinition, QuestionType, SectionDefinition, SubsectionDefinition

PROCESSING_SECTION = SectionDefinition(
    key="processing",
    title="Processing",
    description="Configure warehouse processing levels, grading, data capture, and rework operations.",
    order=3,
    subsections=[
        # ── Level 1 Processing ──────────────────────────────────────────
        SubsectionDefinition(
            key="level_1",
            title="Level 1 Processing",
            order=1,
            questions=[
                QuestionDefinition(
                    key="proc_l1_sorting_location",
                    section="processing",
                    subsection="level_1",
                    question_text="What is the sorting location name for Level 1 processing?",
                    question_type=QuestionType.TEXT,
                    required=True,
                    placeholder="e.g. Tilburg Hub",
                    order=1,
                    target_service="sca-process-models",
                    config_description="Configure sorting location in generic_sorting_matrix",
                ),
                QuestionDefinition(
                    key="proc_l1_rma_required",
                    section="processing",
                    subsection="level_1",
                    question_text="Is the RMA needed on parcels for customs or internal processing?",
                    question_type=QuestionType.BOOLEAN,
                    required=True,
                    order=2,
                    target_service="sca-process-models",
                    config_description="Configure RMA label in print_client_label_config",
                ),
                QuestionDefinition(
                    key="proc_customs_in_scope",
                    section="processing",
                    subsection="level_1",
                    question_text="Are customs checks in scope?",
                    question_type=QuestionType.BOOLEAN,
                    required=True,
                    help_text="Enables Level 1 customs checking, Katana PIM usage, and customs label sorting.",
                    order=3,
                    target_service="sca-process-models",
                    config_description="Configure customs check in generic_sorting_matrix and PIM",
                ),
                QuestionDefinition(
                    key="proc_exception_location",
                    section="processing",
                    subsection="level_1",
                    question_text="To which location should exception parcels be sorted?",
                    question_type=QuestionType.TEXT,
                    placeholder="e.g. Exception Bay A",
                    order=4,
                    target_service="sca-process-models",
                    config_description="Configure exception sorting type in generic_sorting_matrix",
                ),
            ],
        ),
        # ── Level 2 Sorting & Registration ──────────────────────────────
        SubsectionDefinition(
            key="level_2_sorting",
            title="Level 2 Sorting & Registration",
            order=2,
            questions=[
                QuestionDefinition(
                    key="proc_l2_sorting_locations",
                    section="processing",
                    subsection="level_2_sorting",
                    question_text="How many sorting locations are needed?",
                    question_type=QuestionType.TEXT,
                    required=True,
                    help_text="Enter the names of all Level 2 sorting locations, separated by commas.",
                    placeholder="e.g. Location A, Location B",
                    order=1,
                    target_service="sca-process-models",
                    config_description="Configure sorting types and VAS in generic_sorting_matrix",
                ),
                QuestionDefinition(
                    key="proc_barcode_type",
                    section="processing",
                    subsection="level_2_sorting",
                    question_text="Do all items have a scannable EAN or SKU barcode?",
                    question_type=QuestionType.SELECT,
                    options=["EAN", "SKU", "Both"],
                    required=True,
                    order=2,
                    target_service="sca-process-models",
                    config_description="Configure scannable fields in standard_vas_config",
                ),
                QuestionDefinition(
                    key="proc_expected_item_source",
                    section="processing",
                    subsection="level_2_sorting",
                    question_text="What is considered an expected item?",
                    question_type=QuestionType.SELECT,
                    options=["Returns Parcel", "Order"],
                    required=True,
                    order=3,
                    target_service="sca-process-models",
                    config_description="Configure item retrieval in parcel_initialiser_get_items_config",
                ),
                QuestionDefinition(
                    key="proc_sorting_level",
                    section="processing",
                    subsection="level_2_sorting",
                    question_text="Should items be removed from the parcel for sorting?",
                    question_type=QuestionType.SELECT,
                    options=["Parcel-level sorting", "Item-level sorting"],
                    required=True,
                    order=4,
                    target_service="sca-process-models",
                    config_description="Configure sorting config in standard_vas_sorting_config",
                ),
                QuestionDefinition(
                    key="proc_unexpected_item_action",
                    section="processing",
                    subsection="level_2_sorting",
                    question_text="What happens to unexpected items during parcel-level sorting?",
                    question_type=QuestionType.SELECT,
                    options=["Separate", "Keep in parcel"],
                    depends_on={"proc_sorting_level": "Parcel-level sorting"},
                    order=5,
                    target_service="sca-process-models",
                    config_description="Configure expected item flags in sorting config",
                ),
                QuestionDefinition(
                    key="proc_processing_level",
                    section="processing",
                    subsection="level_2_sorting",
                    question_text="Which processing level is required?",
                    question_type=QuestionType.SELECT,
                    options=["Level 1 only", "Level 1 + Level 2", "Level 1 + Level 2 + Level 3"],
                    required=True,
                    help_text="Controls which processing sections are applicable.",
                    order=6,
                    config_description="Controls questionnaire flow",
                ),
                QuestionDefinition(
                    key="proc_product_types",
                    section="processing",
                    subsection="level_2_sorting",
                    question_text="What product types does the client have?",
                    question_type=QuestionType.TEXT,
                    help_text="Informational — helps ReBound plan processing resources.",
                    placeholder="e.g. Clothing, Footwear, Accessories",
                    order=7,
                ),
            ],
        ),
        # ── Grading ─────────────────────────────────────────────────────
        SubsectionDefinition(
            key="grading",
            title="Grading",
            order=3,
            questions=[
                QuestionDefinition(
                    key="proc_grading_in_scope",
                    section="processing",
                    subsection="grading",
                    question_text="Is grading in scope?",
                    question_type=QuestionType.BOOLEAN,
                    required=True,
                    depends_on={"proc_processing_level": ["Level 1 + Level 2", "Level 1 + Level 2 + Level 3"]},
                    order=1,
                    target_service="sca-process-models",
                    config_description="Configure client in item_grading_config",
                ),
                QuestionDefinition(
                    key="proc_grading_type",
                    section="processing",
                    subsection="grading",
                    question_text="What grading system should be used?",
                    question_type=QuestionType.SELECT,
                    options=["A / B / C", "Pass / Fail"],
                    depends_on={"proc_grading_in_scope": True},
                    order=2,
                    target_service="sca-process-models",
                    config_description="Configure grading type in item_grading_config",
                ),
                QuestionDefinition(
                    key="proc_grading_sop",
                    section="processing",
                    subsection="grading",
                    question_text="Which grading SOP should be used?",
                    question_type=QuestionType.SELECT,
                    options=["Client SOP", "ReBound Standard"],
                    depends_on={"proc_grading_in_scope": True},
                    help_text="Client SOP requires uploading custom grading instructions.",
                    order=3,
                    target_service="sca-process-models",
                    config_description="Configure SOP in item_grading_config",
                ),
                QuestionDefinition(
                    key="proc_graded_items_scope",
                    section="processing",
                    subsection="grading",
                    question_text="Which items must be graded?",
                    question_type=QuestionType.SELECT,
                    options=["All items", "Expected only", "Unexpected only", "By item type", "By brand"],
                    depends_on={"proc_grading_in_scope": True},
                    order=4,
                    target_service="sca-process-models",
                    config_description="Configure grading scope in item_grading_config",
                ),
                QuestionDefinition(
                    key="proc_c_grade_reasons",
                    section="processing",
                    subsection="grading",
                    question_text="Should C-grade or fail reasons be captured?",
                    question_type=QuestionType.BOOLEAN,
                    depends_on={"proc_grading_in_scope": True},
                    order=5,
                    target_service="sca-process-models",
                    config_description="Enable reason capture in item_grading_config",
                ),
            ],
        ),
        # ── Data Capture & Labels ───────────────────────────────────────
        SubsectionDefinition(
            key="data_capture_labels",
            title="Data Capture & Labels",
            order=4,
            questions=[
                QuestionDefinition(
                    key="proc_capture_fields",
                    section="processing",
                    subsection="data_capture_labels",
                    question_text="What data should be captured during processing?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=["Category", "Brand", "Product ID", "Country of Origin", "Date", "Return Reason"],
                    depends_on={"proc_processing_level": ["Level 1 + Level 2", "Level 1 + Level 2 + Level 3"]},
                    order=1,
                    target_service="sca-process-models",
                    config_description="Enable data capture flags in data_capture_config",
                ),
                QuestionDefinition(
                    key="proc_categories",
                    section="processing",
                    subsection="data_capture_labels",
                    question_text="List product categories (up to 5)",
                    question_type=QuestionType.TEXT,
                    depends_on={"proc_processing_level": ["Level 1 + Level 2", "Level 1 + Level 2 + Level 3"]},
                    placeholder="e.g. Tops, Bottoms, Shoes, Accessories",
                    order=2,
                    target_service="sca-process-models",
                    config_description="Store categories in data_capture_config",
                ),
                QuestionDefinition(
                    key="proc_brands",
                    section="processing",
                    subsection="data_capture_labels",
                    question_text="List brands (up to 5)",
                    question_type=QuestionType.TEXT,
                    depends_on={"proc_processing_level": ["Level 1 + Level 2", "Level 1 + Level 2 + Level 3"]},
                    placeholder="e.g. Nike, Adidas, Puma",
                    order=3,
                    target_service="sca-process-models",
                    config_description="Store brands in data_capture_config",
                ),
                QuestionDefinition(
                    key="proc_product_id_help",
                    section="processing",
                    subsection="data_capture_labels",
                    question_text="Where is the product ID located on the item?",
                    question_type=QuestionType.TEXTAREA,
                    depends_on={"proc_processing_level": ["Level 1 + Level 2", "Level 1 + Level 2 + Level 3"]},
                    help_text="Provide instructions for warehouse staff to find the product ID.",
                    order=4,
                    target_service="sca-process-models",
                    config_description="Configure ProductId Tip instructions",
                ),
                QuestionDefinition(
                    key="proc_return_reasons",
                    section="processing",
                    subsection="data_capture_labels",
                    question_text="List reasons for return (up to 5)",
                    question_type=QuestionType.TEXT,
                    depends_on={"proc_processing_level": ["Level 1 + Level 2", "Level 1 + Level 2 + Level 3"]},
                    placeholder="e.g. Too small, Defective, Changed mind",
                    order=5,
                    target_service="sca-process-models",
                    config_description="Configure return reasons per client",
                ),
                QuestionDefinition(
                    key="proc_rma_label_required",
                    section="processing",
                    subsection="data_capture_labels",
                    question_text="Do you need RMA labels on items or parcels?",
                    question_type=QuestionType.BOOLEAN,
                    depends_on={"proc_processing_level": ["Level 1 + Level 2", "Level 1 + Level 2 + Level 3"]},
                    order=6,
                    target_service="sca-process-models",
                    config_description="Configure client in print_client_label_config",
                ),
                QuestionDefinition(
                    key="proc_label_specs",
                    section="processing",
                    subsection="data_capture_labels",
                    question_text="Provide label specifications",
                    question_type=QuestionType.TEXTAREA,
                    depends_on={"proc_rma_label_required": True},
                    placeholder="Describe label size, content, and placement requirements",
                    order=7,
                    target_service="sca-process-models",
                    config_description="Configure label template in Standard VAS Printing Config",
                ),
            ],
        ),
        # ── Level 3 Rework ──────────────────────────────────────────────
        SubsectionDefinition(
            key="level_3_rework",
            title="Level 3 Rework",
            order=5,
            questions=[
                QuestionDefinition(
                    key="proc_l3_all_lanes",
                    section="processing",
                    subsection="level_3_rework",
                    question_text="Is Level 3 rework in scope for all lanes?",
                    question_type=QuestionType.BOOLEAN,
                    depends_on={"proc_processing_level": "Level 1 + Level 2 + Level 3"},
                    order=1,
                    target_service="sca-process-models",
                    config_description="Configure client in Standard VAS Rework Item Config",
                ),
                QuestionDefinition(
                    key="proc_l3_category_scope",
                    section="processing",
                    subsection="level_3_rework",
                    question_text="Is Level 3 limited to specific categories?",
                    question_type=QuestionType.SELECT,
                    options=["All categories", "Specific categories"],
                    depends_on={"proc_l3_all_lanes": True},
                    order=2,
                    target_service="sca-process-models",
                    config_description="Configure category + grade in Rework Item Config",
                ),
                QuestionDefinition(
                    key="proc_polybag_replacement",
                    section="processing",
                    subsection="level_3_rework",
                    question_text="Must all polybags be replaced?",
                    question_type=QuestionType.SELECT,
                    options=["Yes — all polybags", "Only damaged polybags"],
                    depends_on={"proc_processing_level": "Level 1 + Level 2 + Level 3"},
                    order=3,
                    target_service="sca-process-models",
                    config_description="Configure package grading in Package Grading Config",
                ),
                QuestionDefinition(
                    key="proc_retagging_scope",
                    section="processing",
                    subsection="level_3_rework",
                    question_text="Which items require retagging?",
                    question_type=QuestionType.TEXT,
                    depends_on={"proc_processing_level": "Level 1 + Level 2 + Level 3"},
                    placeholder="e.g. All items, Grade A only",
                    order=4,
                    target_service="sca-process-models",
                    config_description="Configure printing and item relabelling config",
                ),
                QuestionDefinition(
                    key="proc_box_replacement",
                    section="processing",
                    subsection="level_3_rework",
                    question_text="Do all boxes need replacement?",
                    question_type=QuestionType.BOOLEAN,
                    depends_on={"proc_processing_level": "Level 1 + Level 2 + Level 3"},
                    order=5,
                    config_description="Informational — no automated action",
                ),
                QuestionDefinition(
                    key="proc_consumables_provided",
                    section="processing",
                    subsection="level_3_rework",
                    question_text="Are consumables client-provided?",
                    question_type=QuestionType.BOOLEAN,
                    depends_on={"proc_processing_level": "Level 1 + Level 2 + Level 3"},
                    help_text="E.g. polybags, tissue paper, hangers.",
                    order=6,
                    config_description="Informational — no automated action",
                ),
                QuestionDefinition(
                    key="proc_label_scope",
                    section="processing",
                    subsection="level_3_rework",
                    question_text="Should license plates be at parcel or item level?",
                    question_type=QuestionType.SELECT,
                    options=["Parcel", "Item"],
                    depends_on={"proc_processing_level": "Level 1 + Level 2 + Level 3"},
                    order=7,
                    config_description="Informational — no automated action",
                ),
                QuestionDefinition(
                    key="proc_extra_capture",
                    section="processing",
                    subsection="level_3_rework",
                    question_text="Capture extra item information?",
                    question_type=QuestionType.BOOLEAN,
                    depends_on={"proc_processing_level": ["Level 1 + Level 2", "Level 1 + Level 2 + Level 3"]},
                    order=8,
                    config_description="Controls additional data capture visibility",
                ),
            ],
        ),
    ],
)
