from app.questions.types import QuestionDefinition, QuestionType, SectionDefinition, SubsectionDefinition

PROCESSING_SECTION = SectionDefinition(
    key="processing",
    title="Processing",
    description="Configure warehouse processing levels, grading, data capture, and rework operations.",
    order=3,
    subsections=[
        SubsectionDefinition(
            key="general",
            title="General Processing",
            order=1,
            questions=[
                QuestionDefinition(
                    key="pr_product_types",
                    section="processing",
                    subsection="general",
                    question_text="What types of products do you sell?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=["Footwear", "Apparel", "Electronics", "Accessories", "Home Goods", "Beauty", "Other"],
                    required=True,
                    help_text="Select all product types. This determines processing rules.",
                    order=1,
                ),
                QuestionDefinition(
                    key="pr_processing_level",
                    section="processing",
                    subsection="general",
                    question_text="Which processing level is required?",
                    question_type=QuestionType.SELECT,
                    options=["Level 1 (Parcel level)", "Level 2 (Item registration)", "Level 2 (Item grading)", "Level 3 (Rework/Retagging)"],
                    required=True,
                    help_text="L1: Parcel sorting only. L2: Item-level inspection. L3: Full rework including retagging.",
                    order=2,
                    config_description="Configures processing level in warehouse-service",
                ),
                QuestionDefinition(
                    key="pr_high_value_processing",
                    section="processing",
                    subsection="general",
                    question_text="Different processing level for high-value returns?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No"],
                    required=False,
                    order=3,
                ),
                QuestionDefinition(
                    key="pr_high_value_threshold",
                    section="processing",
                    subsection="general",
                    question_text="High-value threshold (EUR per parcel)?",
                    question_type=QuestionType.NUMBER,
                    required=True,
                    depends_on={"pr_high_value_processing": "Yes"},
                    placeholder="100",
                    order=4,
                ),
            ],
        ),
        SubsectionDefinition(
            key="level_1_parcel",
            title="Level 1 — Parcel Processing",
            order=2,
            questions=[
                QuestionDefinition(
                    key="pr_l1_sorting_location",
                    section="processing",
                    subsection="level_1_parcel",
                    question_text="Sorting location name for Level 1 processing",
                    question_type=QuestionType.TEXT,
                    required=True,
                    help_text="Name of the sorting destination in the warehouse system.",
                    placeholder="e.g., CLIENT_MAIN_SORT",
                    order=1,
                    config_description="Configures sorting type in generic_sorting_matrix",
                ),
                QuestionDefinition(
                    key="pr_l1_rma_on_parcel",
                    section="processing",
                    subsection="level_1_parcel",
                    question_text="Do you need the RMA number on parcel labels?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No"],
                    required=True,
                    help_text="RMA can be printed on labels for identification during customs or processing.",
                    order=2,
                    config_description="Configures RMA label in print_client_label_config",
                ),
                QuestionDefinition(
                    key="pr_l1_customs_in_scope",
                    section="processing",
                    subsection="level_1_parcel",
                    question_text="Are customs checks in scope?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No"],
                    required=True,
                    help_text="If yes, Level 2 registration will be activated for exception parcels to gather customs data.",
                    order=3,
                    config_description="Configures customs check in generic_sorting_matrix",
                ),
            ],
        ),
        SubsectionDefinition(
            key="level_2_registration",
            title="Level 2 — Item Registration",
            order=3,
            questions=[
                QuestionDefinition(
                    key="pr_l2_sorting_locations",
                    section="processing",
                    subsection="level_2_registration",
                    question_text="How many sorting locations are needed? Provide names (up to 3).",
                    question_type=QuestionType.TEXTAREA,
                    required=True,
                    depends_on={"pr_processing_level": ["Level 2 (Item registration)", "Level 2 (Item grading)", "Level 3 (Rework/Retagging)"]},
                    placeholder="GOOD_STOCK\nDAMAGED\nQUARANTINE",
                    order=1,
                    config_description="Configures sorting types in generic_sorting_matrix",
                ),
                QuestionDefinition(
                    key="pr_l2_barcode_type",
                    section="processing",
                    subsection="level_2_registration",
                    question_text="Do items have a scannable barcode?",
                    question_type=QuestionType.SELECT,
                    options=["EAN", "SKU", "Both EAN and SKU", "Neither"],
                    required=True,
                    depends_on={"pr_processing_level": ["Level 2 (Item registration)", "Level 2 (Item grading)", "Level 3 (Rework/Retagging)"]},
                    help_text="Determines how items are identified during scanning.",
                    order=2,
                    config_description="Configures scannable fields in standard_vas_config",
                ),
                QuestionDefinition(
                    key="pr_l2_sorting_level",
                    section="processing",
                    subsection="level_2_registration",
                    question_text="Should items be sorted at item level or parcel level?",
                    question_type=QuestionType.SELECT,
                    options=["Item level", "Parcel level"],
                    required=True,
                    depends_on={"pr_processing_level": ["Level 2 (Item registration)", "Level 2 (Item grading)", "Level 3 (Rework/Retagging)"]},
                    help_text="Item level: items sorted individually into boxes. Parcel level: items stay in parcel.",
                    order=3,
                    config_description="Configures sorting level in standard_vas_sorting_config",
                ),
            ],
        ),
        SubsectionDefinition(
            key="level_2_grading",
            title="Level 2 — Item Grading",
            order=4,
            questions=[
                QuestionDefinition(
                    key="pr_l2_grading_in_scope",
                    section="processing",
                    subsection="level_2_grading",
                    question_text="Is item grading in scope?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No"],
                    required=True,
                    depends_on={"pr_processing_level": ["Level 2 (Item grading)", "Level 3 (Rework/Retagging)"]},
                    help_text="Grading assesses the condition of returned items.",
                    order=1,
                    config_description="Configures grading in item_grading_config",
                ),
                QuestionDefinition(
                    key="pr_l2_grading_type",
                    section="processing",
                    subsection="level_2_grading",
                    question_text="Which grading system?",
                    question_type=QuestionType.SELECT,
                    options=["A/B/C", "Pass/Fail"],
                    required=True,
                    depends_on={"pr_l2_grading_in_scope": "Yes"},
                    help_text="A/B/C: three-tier. Pass/Fail: binary assessment.",
                    order=2,
                    config_description="Configures grading type in item_grading_config",
                ),
                QuestionDefinition(
                    key="pr_l2_grading_sop",
                    section="processing",
                    subsection="level_2_grading",
                    question_text="Grading SOP provider?",
                    question_type=QuestionType.SELECT,
                    options=["Client provides SOP", "Use ReBound standard"],
                    required=True,
                    depends_on={"pr_l2_grading_in_scope": "Yes"},
                    order=3,
                ),
                QuestionDefinition(
                    key="pr_l2_photo_evidence",
                    section="processing",
                    subsection="level_2_grading",
                    question_text="Should photos be taken for C-grade / failed items?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No"],
                    required=False,
                    depends_on={"pr_l2_grading_in_scope": "Yes"},
                    order=4,
                ),
            ],
        ),
        SubsectionDefinition(
            key="level_2_data_capture",
            title="Level 2 — Data Capture",
            order=5,
            questions=[
                QuestionDefinition(
                    key="pr_l2_extra_data",
                    section="processing",
                    subsection="level_2_data_capture",
                    question_text="Capture extra item data when missing from pre-alert?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No"],
                    required=True,
                    depends_on={"pr_processing_level": ["Level 2 (Item registration)", "Level 2 (Item grading)", "Level 3 (Rework/Retagging)"]},
                    order=1,
                ),
                QuestionDefinition(
                    key="pr_l2_data_fields",
                    section="processing",
                    subsection="level_2_data_capture",
                    question_text="Which data fields should be captured?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=["Product Category", "Product ID", "Brand", "Country of Origin", "Date of Purchase", "Return Reason"],
                    required=True,
                    depends_on={"pr_l2_extra_data": "Yes"},
                    order=2,
                    config_description="Configures capture fields in data_capture_config",
                ),
            ],
        ),
        SubsectionDefinition(
            key="level_3_rework",
            title="Level 3 — Rework",
            order=6,
            questions=[
                QuestionDefinition(
                    key="pr_l3_scope",
                    section="processing",
                    subsection="level_3_rework",
                    question_text="Is L3 rework in scope for all return lanes?",
                    question_type=QuestionType.SELECT,
                    options=["Yes - all lanes", "No - specific lanes only"],
                    required=True,
                    depends_on={"pr_processing_level": "Level 3 (Rework/Retagging)"},
                    order=1,
                    config_description="Configures rework scope in Standard_VAS_Rework_Item_Config",
                ),
                QuestionDefinition(
                    key="pr_l3_polybag",
                    section="processing",
                    subsection="level_3_rework",
                    question_text="Polybag replacement policy?",
                    question_type=QuestionType.SELECT,
                    options=["Replace all", "Replace only if damaged"],
                    required=True,
                    depends_on={"pr_processing_level": "Level 3 (Rework/Retagging)"},
                    order=2,
                    config_description="Configures package grading in Package_Grading_Config",
                ),
                QuestionDefinition(
                    key="pr_l3_retagging",
                    section="processing",
                    subsection="level_3_rework",
                    question_text="Which items require retagging?",
                    question_type=QuestionType.TEXTAREA,
                    required=True,
                    depends_on={"pr_processing_level": "Level 3 (Rework/Retagging)"},
                    placeholder="e.g., All apparel. Footwear requires hang tags.",
                    order=3,
                    config_description="Configures retagging in Standard_VAS_Printing_Config",
                ),
                QuestionDefinition(
                    key="pr_l3_consumables",
                    section="processing",
                    subsection="level_3_rework",
                    question_text="Who provides consumables (polybags, boxes, labels)?",
                    question_type=QuestionType.SELECT,
                    options=["Client provides", "ReBound provides"],
                    required=False,
                    depends_on={"pr_processing_level": "Level 3 (Rework/Retagging)"},
                    order=4,
                ),
            ],
        ),
    ],
)
