from app.questions.types import QuestionDefinition, QuestionType, SectionDefinition, SubsectionDefinition

RETURN_INITIATION_SECTION = SectionDefinition(
    key="return_initiation",
    title="Return Initiation",
    description="Configure the return portal, consumer flow, and customer success tools.",
    order=1,
    subsections=[
        SubsectionDefinition(
            key="setup",
            title="Setup",
            order=1,
            questions=[
                QuestionDefinition(
                    key="ri_frontend",
                    section="return_initiation",
                    subsection="setup",
                    question_text="Which frontend will be used?",
                    question_type=QuestionType.SELECT,
                    options=["ReBound Consumer Portal", "Partner Portal", "Client Portal"],
                    required=True,
                    order=1,
                    target_service="unicorn",
                    config_description="Configure frontend type in Unicorn",
                ),
                QuestionDefinition(
                    key="ri_partner",
                    section="return_initiation",
                    subsection="setup",
                    question_text="Which partner will be used?",
                    question_type=QuestionType.SELECT,
                    options=["Narvar", "Loop", "ReturnGo", "nShift", "Other"],
                    depends_on={"ri_frontend": "Partner Portal"},
                    order=2,
                    target_service="unicorn",
                    config_description="Configure partner integration in Unicorn",
                ),
                QuestionDefinition(
                    key="ri_api_integration",
                    section="return_initiation",
                    subsection="setup",
                    question_text="What API integration is needed?",
                    question_type=QuestionType.SELECT,
                    options=["HAPI", "Order Service"],
                    required=True,
                    order=3,
                    target_service="unicorn",
                    config_description="Configure API integration type",
                ),
                QuestionDefinition(
                    key="ri_order_sync_direction",
                    section="return_initiation",
                    subsection="setup",
                    question_text="Do you want to push or pull order data?",
                    question_type=QuestionType.SELECT,
                    options=["Push", "Pull"],
                    depends_on={"ri_frontend": "ReBound Consumer Portal"},
                    order=4,
                    target_service="unicorn",
                    config_description="Configure order data sync direction",
                ),
                QuestionDefinition(
                    key="ri_customs_lanes",
                    section="return_initiation",
                    subsection="setup",
                    question_text="Are customs lanes in scope?",
                    question_type=QuestionType.BOOLEAN,
                    required=True,
                    order=5,
                    config_description="Enable customs lane processing",
                ),
                QuestionDefinition(
                    key="ri_rgr_in_scope",
                    section="return_initiation",
                    subsection="setup",
                    question_text="Is Returned Goods Relief (RGR) in scope?",
                    question_type=QuestionType.BOOLEAN,
                    required=True,
                    help_text="RGR allows duty-free re-importation of goods previously exported from the UK/EU.",
                    order=6,
                    config_description="Enable RGR processing",
                ),
                QuestionDefinition(
                    key="ri_refund_trigger",
                    section="return_initiation",
                    subsection="setup",
                    question_text="Do you want refund triggers?",
                    question_type=QuestionType.BOOLEAN,
                    required=True,
                    order=7,
                    config_description="Enable automated refund triggers",
                ),
                QuestionDefinition(
                    key="ri_refund_level",
                    section="return_initiation",
                    subsection="setup",
                    question_text="At what level should refunds be triggered?",
                    question_type=QuestionType.SELECT,
                    options=["Parcel", "Item"],
                    depends_on={"ri_refund_trigger": True},
                    order=8,
                    config_description="Configure refund trigger granularity",
                ),
            ],
        ),
        SubsectionDefinition(
            key="consumer_portal",
            title="Consumer Portal",
            order=2,
            questions=[
                QuestionDefinition(
                    key="ri_portal_journey",
                    section="return_initiation",
                    subsection="consumer_portal",
                    question_text="What user journey would you like to set up?",
                    question_type=QuestionType.SELECT,
                    options=["Order Lookup", "Order History Preview"],
                    depends_on={"ri_frontend": "ReBound Consumer Portal"},
                    order=1,
                    config_description="Configure consumer portal journey type",
                ),
                QuestionDefinition(
                    key="ri_dropoff_map",
                    section="return_initiation",
                    subsection="consumer_portal",
                    question_text="Display a map showing nearby drop-off points?",
                    question_type=QuestionType.BOOLEAN,
                    help_text="Shows consumers a map of nearby carrier drop-off locations.",
                    order=2,
                    config_description="Enable drop-off point map on portal",
                ),
                QuestionDefinition(
                    key="ri_return_payer",
                    section="return_initiation",
                    subsection="consumer_portal",
                    question_text="Who should pay for the return?",
                    question_type=QuestionType.SELECT,
                    options=["Retailer", "Consumer"],
                    required=True,
                    order=3,
                    config_description="Configure return cost responsibility",
                ),
                QuestionDefinition(
                    key="ri_consumer_payment_method",
                    section="return_initiation",
                    subsection="consumer_portal",
                    question_text="How does the consumer pay for the return?",
                    question_type=QuestionType.SELECT,
                    options=["Directly", "Deduct from Refund"],
                    depends_on={"ri_return_payer": "Consumer"},
                    order=4,
                    config_description="Configure consumer payment method",
                ),
                QuestionDefinition(
                    key="ri_payment_recipient",
                    section="return_initiation",
                    subsection="consumer_portal",
                    question_text="Who should receive the payment?",
                    question_type=QuestionType.SELECT,
                    options=["Client", "ReBound"],
                    depends_on={"ri_return_payer": "Consumer"},
                    order=5,
                    config_description="Configure payment recipient",
                ),
            ],
        ),
        SubsectionDefinition(
            key="cs_portal",
            title="Customer Success Portal",
            order=3,
            questions=[
                QuestionDefinition(
                    key="ri_cs_portal_enabled",
                    section="return_initiation",
                    subsection="cs_portal",
                    question_text="Do you need a customer success portal?",
                    question_type=QuestionType.BOOLEAN,
                    required=True,
                    order=1,
                    config_description="Enable customer success portal",
                    target_service="keycloak",
                ),
                QuestionDefinition(
                    key="ri_cs_portal_features",
                    section="return_initiation",
                    subsection="cs_portal",
                    question_text="What functionality do you want on the customer success portal?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=[
                        "Look up an order",
                        "Register a return for a consumer",
                        "Search for a parcel",
                        "Get tracking updates",
                        "Cancel a return",
                    ],
                    depends_on={"ri_cs_portal_enabled": True},
                    order=2,
                    config_description="Configure CS portal features",
                ),
                QuestionDefinition(
                    key="ri_cs_user_emails",
                    section="return_initiation",
                    subsection="cs_portal",
                    question_text="Provide the email addresses of customer success portal users",
                    question_type=QuestionType.EMAIL_LIST,
                    depends_on={"ri_cs_portal_enabled": True},
                    help_text="Enter email addresses of users who need access to the CS portal.",
                    order=3,
                    target_service="keycloak",
                    config_description="Create CS portal user accounts in Keycloak",
                ),
            ],
        ),
    ],
)
