from app.questions.types import QuestionDefinition, QuestionType, SectionDefinition, SubsectionDefinition

RETURN_INITIATION_SECTION = SectionDefinition(
    key="return_initiation",
    title="Return Initiation",
    description="Configure how consumers initiate returns through your portal and define return policies.",
    order=1,
    subsections=[
        SubsectionDefinition(
            key="portal_config",
            title="Portal Configuration",
            order=1,
            questions=[
                QuestionDefinition(
                    key="ri_portal_type",
                    section="return_initiation",
                    subsection="portal_config",
                    question_text="Which return portal will be used?",
                    question_type=QuestionType.SELECT,
                    options=["ReBound Portal", "Client-owned Portal", "Third-party (e.g., Narvar, Loop)"],
                    required=True,
                    help_text="Select the portal that consumers will use to initiate returns.",
                    order=1,
                    config_description="Configures portal type in return-initiation-service",
                ),
                QuestionDefinition(
                    key="ri_portal_url",
                    section="return_initiation",
                    subsection="portal_config",
                    question_text="What is the return portal URL?",
                    question_type=QuestionType.TEXT,
                    required=True,
                    depends_on={"ri_portal_type": ["Client-owned Portal", "Third-party (e.g., Narvar, Loop)"]},
                    help_text="Provide the URL of the external return portal.",
                    placeholder="https://returns.yourstore.com",
                    order=2,
                ),
                QuestionDefinition(
                    key="ri_portal_branding",
                    section="return_initiation",
                    subsection="portal_config",
                    question_text="Should the portal use your brand colors and logo?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No - use ReBound default"],
                    required=True,
                    depends_on={"ri_portal_type": "ReBound Portal"},
                    help_text="If yes, we will apply your brand guidelines to the return portal.",
                    order=3,
                    config_description="Configures portal branding in portal-service",
                ),
                QuestionDefinition(
                    key="ri_portal_languages",
                    section="return_initiation",
                    subsection="portal_config",
                    question_text="Which languages should the portal support?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=["English", "German", "French", "Dutch", "Spanish", "Italian", "Portuguese", "Swedish"],
                    required=True,
                    help_text="Select all languages needed for your consumer-facing portal.",
                    order=4,
                    config_description="Configures language support in portal-service",
                ),
            ],
        ),
        SubsectionDefinition(
            key="consumer_flow",
            title="Consumer Flow",
            order=2,
            questions=[
                QuestionDefinition(
                    key="ri_auth_method",
                    section="return_initiation",
                    subsection="consumer_flow",
                    question_text="How should consumers authenticate to start a return?",
                    question_type=QuestionType.SELECT,
                    options=["Order number + email", "Order number + postcode", "Login to account", "No authentication"],
                    required=True,
                    help_text="This determines how consumers verify their identity before initiating a return.",
                    order=1,
                    config_description="Configures consumer auth in portal-service",
                ),
                QuestionDefinition(
                    key="ri_return_reason_required",
                    section="return_initiation",
                    subsection="consumer_flow",
                    question_text="Should consumers provide a return reason?",
                    question_type=QuestionType.SELECT,
                    options=["Yes - mandatory", "Yes - optional", "No"],
                    required=True,
                    help_text="Return reasons help with quality insights and processing decisions.",
                    order=2,
                ),
                QuestionDefinition(
                    key="ri_return_reasons",
                    section="return_initiation",
                    subsection="consumer_flow",
                    question_text="List the return reasons available to consumers",
                    question_type=QuestionType.TEXTAREA,
                    required=True,
                    depends_on={"ri_return_reason_required": ["Yes - mandatory", "Yes - optional"]},
                    help_text="Enter one reason per line.",
                    placeholder="Too small\nToo large\nDefective\nNot as described\nChanged mind",
                    order=3,
                ),
                QuestionDefinition(
                    key="ri_photo_upload",
                    section="return_initiation",
                    subsection="consumer_flow",
                    question_text="Should consumers upload photos of the item?",
                    question_type=QuestionType.SELECT,
                    options=["Yes - mandatory", "Yes - optional", "No"],
                    required=True,
                    help_text="Photos can be used for pre-grading and dispute resolution.",
                    order=4,
                ),
                QuestionDefinition(
                    key="ri_item_selection",
                    section="return_initiation",
                    subsection="consumer_flow",
                    question_text="Can consumers select individual items to return from an order?",
                    question_type=QuestionType.SELECT,
                    options=["Yes - item-level selection", "No - full order only"],
                    required=True,
                    help_text="Item-level selection allows partial returns.",
                    order=5,
                    config_description="Configures item selection in portal-service",
                ),
            ],
        ),
        SubsectionDefinition(
            key="return_policies",
            title="Return Policies",
            order=3,
            questions=[
                QuestionDefinition(
                    key="ri_return_window",
                    section="return_initiation",
                    subsection="return_policies",
                    question_text="What is the return window (days from delivery)?",
                    question_type=QuestionType.NUMBER,
                    required=True,
                    help_text="Standard is 14-30 days. Enter the number of days.",
                    placeholder="30",
                    order=1,
                    config_description="Configures return window in policy-service",
                ),
                QuestionDefinition(
                    key="ri_extended_return",
                    section="return_initiation",
                    subsection="return_policies",
                    question_text="Do you offer extended return windows (e.g., holiday season)?",
                    question_type=QuestionType.SELECT,
                    options=["Yes", "No"],
                    required=True,
                    help_text="Extended windows typically apply during November-January.",
                    order=2,
                ),
                QuestionDefinition(
                    key="ri_extended_return_days",
                    section="return_initiation",
                    subsection="return_policies",
                    question_text="Extended return window (days from delivery)",
                    question_type=QuestionType.NUMBER,
                    required=True,
                    depends_on={"ri_extended_return": "Yes"},
                    placeholder="60",
                    order=3,
                ),
                QuestionDefinition(
                    key="ri_non_returnable",
                    section="return_initiation",
                    subsection="return_policies",
                    question_text="Are any product categories non-returnable?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=["Underwear", "Swimwear", "Pierced jewelry", "Perishable goods", "Customized items", "None"],
                    required=True,
                    help_text="Select categories that cannot be returned.",
                    order=4,
                    config_description="Configures non-returnable items in policy-service",
                ),
                QuestionDefinition(
                    key="ri_refund_method",
                    section="return_initiation",
                    subsection="return_policies",
                    question_text="What refund methods are available?",
                    question_type=QuestionType.MULTI_SELECT,
                    options=["Original payment method", "Store credit", "Exchange", "Gift card"],
                    required=True,
                    help_text="Select all refund options you want to offer consumers.",
                    order=5,
                    config_description="Configures refund methods in payment-service",
                ),
            ],
        ),
        SubsectionDefinition(
            key="authorization",
            title="Authorization & RMA",
            order=4,
            questions=[
                QuestionDefinition(
                    key="ri_rma_required",
                    section="return_initiation",
                    subsection="authorization",
                    question_text="Is Return Merchandise Authorization (RMA) required?",
                    question_type=QuestionType.SELECT,
                    options=["Yes - all returns require RMA", "Yes - only for high-value items", "No - auto-approve"],
                    required=True,
                    help_text="RMA adds a manual approval step before a return label is generated.",
                    order=1,
                    config_description="Configures RMA flow in authorization-service",
                ),
                QuestionDefinition(
                    key="ri_rma_high_value_threshold",
                    section="return_initiation",
                    subsection="authorization",
                    question_text="What is the high-value threshold for RMA (EUR)?",
                    question_type=QuestionType.NUMBER,
                    required=True,
                    depends_on={"ri_rma_required": "Yes - only for high-value items"},
                    placeholder="200",
                    order=2,
                ),
            ],
        ),
    ],
)
